### ISSUE TITLE
add_shortcode best practice

### ISSUE THREAD

**Issue by pablopaul** [DevinVinson/WordPress-Plugin-Boilerplate#131]
Hei, 

I am wondering if we could improve the boilerplate by integrating a example location where to use the "add_shortcode" function, similar to "add_action" and "add_filter".
For my opinion "add_shortcode" belongs to the frontend so it should live in "/plugin-name/public/class-plugin-name.php", what do you think?

![possible location for add_shortcode](https://f.cloud.github.com/assets/635526/1630893/18f8daea-5756-11e3-80cf-6bc66a87b14d.png)

Any recommended best practice out there?

**Comment by pingram3541** [comment]
I'm not really a fan of shortcodes either but alternatively for those looking for a simple method, if you preferred it in your class, just do something like:
`$this->loader->add_action( 'init', $plugin_public, 'yourpluginname_register_shortcodes' );`
And then in your public bp class do:
```
    public function yourpluginname_register_shortcodes(){
      function your_shortcode($atts){
        extract( shortcode_atts( array(
                //your options
        ), $atts ) );
        //do your plugin stuff
      }
      add_shortcode("your-shortcode-name", "your_shortcode");
    }
```
*note: I am in no way saying this is the "preferred" way however.

**Comment by d8v15** [comment]
Are there any examples - even a full application of using the boilerplate e.g. custom types, shortcodes, utility classes, etc.

**Comment by ruturaaj** [comment]
I have a query; perhaps I'm new to the PHP OOP and the way Wordpress handle classes. 

I have a separate class for shortcode and the action is defined in __construct. The function references in the add_shortcode needs to call another function. When I use $this->function_name, nothing works. If I use self::function_name, it works. 

Why so?

Just to give you a better idea, here is a sample code for you to review...

```
class MyShortcode
{
    add_shortcode('my_shortcode', array(__CLASS__, 'render_shortcode'));
}

function render_shortcode($atts) 
{
    $return = $this->another_function();  //does not work
    $return = self::another_function();  //works!
    return $return;
}

function another_function()
{
    return 'Hello World'; 
}

} //end of class

I hope this helps to understand my confusion. Can someone please tell me why self works but $this does not. How can we make $this to work in the scenario mentioned above?

Waiting for your reply...

Cheers,

**Comment by flashadvocate** [comment]
See http://stackoverflow.com/a/17027307
