### ISSUE TITLE
Consider a Grunt Task for The Boilerplate

### ISSUE THREAD

**Issue by tommcfarlin** [DevinVinson/WordPress-Plugin-Boilerplate#135]
From @bradvin:

> I updated the grunt-init template for the boilerplate and tested it
> out and it seems to be working very nicely.
> 
> Check out my post about it: http://themergency.com/wp-dev-advent-day-1/
> 
> Github Repo : https://github.com/fooplugins/grunt-wp-boilerplate

**Comment by skynet** [comment]
+1
