### ISSUE TITLE
Public theme functions

### ISSUE THREAD

**Issue by jonathan-dejong** [DevinVinson/WordPress-Plugin-Boilerplate#218]
Hi!

Love this boilerplate. Began using it a few days ago on a new plugin project and while it takes some getting used to there's just so much to gain. 

I have a question about best practice:
The user should be able to call a function from within their theme (think of it as a function that outputs some interactive elements). Where and how would you put this? 

My current solution is to have a static public function inside the public class (public/class-plugin-name-public.php) and let them call it by

```
Plugin_Name_Public::the_public_function();
```

But it doesn't feel right.. Should I put another file in the public folder which just contains these functions (not in a class) and include it via the load_dependencies() function? By my logic that should mean that they'll be able to call it with just:

```
the_public_function();
```

P.S. I do realize the function name has to be very unique in that case

**Comment by codecowboy** [comment]
@jonathan-dejong @ihorvorotnov could you maybe share some code somewhere which illustrates how you made plugin methods available?

**Comment by jonathan-dejong** [comment]
@codecowboy 

Sure. My approach might not be the best tho as this was completely new ground for me as well :) 

I've created a file in the /public directory in which I for example put this:

```
/**
* Template tag for displaying the filters form
* @return html object
*/
function show_beautiful_filters($post_type = false){

	return Beautiful_Taxonomy_Filters_Public::beautiful_filters($post_type);
}
```
This file is included in the core plugin file pluginname.php (in my case beautiful-taxonomy-filters.php). The same way deactivator, activator etc. etc. are included. 
```
/** The template tags accessible for public use */
require_once plugin_dir_path( __FILE__ ) . 'public/beautiful-taxonomy-filters-functions.php';
```

As you can see, when a user runs the show_beautiful_filters function it just runs a public static function in the pluginname-public.php file and from there on you're in the class and can go about as you wish!

**Comment by codecowboy** [comment]
Thanks @jonathan-dejong I think I am going to do this for speed this time but my concern with this approach is that with a static method, I am not really accessing the instance of the plugin so will not have access to protected methods and instance properties etc.

**Comment by jonathan-dejong** [comment]
I'm not too well versed in OOP yet with all the visibilities etc. but are you sure you cant access a protected or private method etc. with this? The public static function is within the class and I know I am at least accessing private functions from it without troubles.

**Comment by nathanmarks** [comment]
@codecowboy @jonathan-dejong You can use the wordpress hook system also for this

**Comment by jonathan-dejong** [comment]
@nathanmarks Sounds interesting..  do you have any examples/articles?

**Comment by jacquesletesson** [comment]
@jonathan-dejong Amazing topics. Thank you for sharing your final approach. 

Learnt a lot by reading it.

**Comment by codecowboy** [comment]
@jonathan-dejong you cant access instance methods from a static class method so you can't use the ```$this ``` keyword inside a static function (if thats what you meant when you said 'this'). Instead you would use ```self::`` (or in 5.3+ ```static```) This topic actually gets quite complex. You can read more here:

http://php.net/manual/en/language.oop5.static.php
http://stackoverflow.com/questions/151969/when-to-use-self-vs-this

And then if you really want to confuse yourself look up ```static::``` and 'late static binding' ;)

**Comment by codecowboy** [comment]
@fsylum perhaps the line in the code has changed? The line you link to doesn't appear to have anything to do with breadcrumbs.

**Comment by slushman** [comment]
For reference, here's an article about using hooks instead of template tags: http://nacin.com/2010/05/18/rethinking-template-tags-in-plugins/

**Comment by jonathan-dejong** [comment]
@codecowboy haha no by "this" I just meant my approach :) I'm using self:: 
Thanks @slushman for the link! Nacin to the rescue as per usual ;)

**Comment by phylaxis** [comment]
Sorry to re-open this old thread, but I just discovered the boilerplate and I am considering using it in a project, but had a couple new questions. @jonathan-dejong your solution seems like the one that would work for me and in researching it I downloaded your plug-in to look at the code. I noticed you "deprecated" the approach you mention here in version 1.2.6 of your plug-in. Did you switch to one of the other approaches discussed here or do something else? Can you provide some details or code samples? Thanks in advance.

**Comment by phylaxis** [comment]
Ok, sorry guess I should have checked the README.txt before my last post. For others who might be interested in the change, and @jonathan-dejong please correct me if I mess this up, it looks like the Wordpress hooks method proposed by @nathanmarks was implemented. So a `$this->loader->add_action('your_function_name', $plugin_public, 'class_function_name');` for each "public" template function is added in the `define_public_hooks()` method of the main class file. Then when you want to use the method inside the theme you call `do_action('your_function_name');`. Did I get this right?

**Comment by jonathan-dejong** [comment]
Hey @phylaxis 

Yepp pretty much. BTF has two "core" functions which are called by doing a do_action hook. These run the OOP public functions inside the public class.

To be fair since this I've moved onto our own boilerplate (also oop) which is a bit less content and code overall (and thus match our style of programming better). 
It's not truly released in public yet but if you want to have a look it's here: xprmnt.tigerton.se

I will likely rewrite the whole of BTFs codebase this year as it's grown a bit messy over time and I need to introduce some more helper functions etc.

**Comment by opolanco23** [comment]
Hey guys,

Looking for some advice.

I have implemented the solution highlighted by @phylaxis but my function requires a parameter be passed to it and it also calls other methods within its class. When I try `do_action(function(parameter)');` I get nothing outputted to the screen. If i use `do_action("myfunction"');` it works but due to the call to a function within the same class it fails. 

My question is should i modify the method calls to use self:: or go a different route because of the parameter that must be passed to the function?

Thanks in advance

**Comment by phylaxis** [comment]
Hey @opolanco23 when you pass the parameters with the `do_action()` call you need to pass them as additional values after the function name you're calling like this:

`do_action( 'get_gd_home_menu_items', true );`

In this example `'get_gd_home_menu_items` is the name of my public function in my plugin and `true` is the value of the parameter I want to pass in. Hope this helps.

**Comment by opolanco23** [comment]
@phylaxis thanks for the quick reply. Ah I see, I also modified the function calls so that they use $this->

now I am just having issue outputting the content returned. echo do_action does not work. 

Thank You

**Comment by phylaxis** [comment]
@opolanco23 That is because actions always just return `true`. See the Wordpress `add_action` documentation: https://developer.wordpress.org/reference/functions/add_action/

You need to just echo right inside your action. I typically will build up an `$output` variable and then do an `echo $output;` as the last line of my function.

If you really want a return value then you probably should be using a `filter` (see https://developer.wordpress.org/reference/functions/add_filter/) and doing an `apply_filters()` call, https://developer.wordpress.org/reference/functions/apply_filters/

**Comment by derekcavaliero** [comment]
Like others in here, kind of new to OOP practices (especially inside WordPress's ecosystem).

I have a version of a plugin that simply initializes itself on a global variable in a mu-plugin file as follows:

`$My_Class_Instance = new My_Class();`

Inside the` __construct()` I hook into init and setup properties on the instance that reference the current logged in users "account" (which is simply a custom post type entry object). 

I need to access the property values inside theme template files - right now I might do something like this in a template file:

`$My_Class_Instance->check_subscription_access()`

I can't wrap my head around where to begin refactoring into this boilerplate. I want to do this to make it easier to separate admin vs. public vs. helper functions and make maintenance easier - I think its mostly just the situation of "I don't know what I don't know". 

Any guidance is very much appreciated, I am trying to get into the habit of always building with scale in mind, and I've worked on Laravel projects where things are more cut and dry on how to go about something like this.
