### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by ryanhellyer** [DevinVinson/WordPress-Plugin-Boilerplate#223]
It would be really handy if you could throw in a plugin slug, plugin name, plugin author etc. etc. and have it automatically spit out a plugin with everything named correctly at http://wppb.io/.

**Comment by nderambure** [comment]
Yep, I suggest changing the $plugin_name variable to $plugin_slug too.

**Comment by codecowboy** [comment]
@cluke009 Can you elaborate a bit on what those sed commands are doing exactly?

Is it transforming ```s/thispart/into-this-part/g``` ?

**Comment by cluke009** [comment]
@codecowboy  its simple replacement as you stated.  I would also like to say that my method wasn't a completely pointless exercise as last time I checked both of those generator sites were using outdated version.

**Comment by DevinVinson** [comment]
Closing this out as wppb.me should handle auto generation completely. I'm hoping to get the same script included into the main site but it isn't a priority as Enrique has been keeping the .me generator updated.
