### ISSUE TITLE
Anonymous functions with PHP 5.3

### ISSUE THREAD

**Issue by elimc** [DevinVinson/WordPress-Plugin-Boilerplate#23]
At some point, you may consider changing the create_function php method to an anonymous function supported in PHP 5.3, in order to improve performance: http://framework.zend.com/issues/browse/ZF-7646 

So you would change . . .

`add_action( 'widgets_init', create_function( '', 'register_widget( "foo_widget" );' ) );`

Into . . .

`add_action( 'widgets_init', function(){ return register_widget( 'a\b\c\My_Widget_Class' ); });`

Plus, you can use namespaces with it.

Source: http://codex.wordpress.org/Widgets_API

**Comment by dannyvankooten** [comment]
Hey @tommcfarlin - wondering if there's a discussion going on about bumping the PHP requirements? 

I recently started requiring PHP 5.3+ for all my new plugins (with a fallback notice for users on 5.3, [example](https://github.com/dannyvankooten/wp-mailchimp-top-bar/blob/master/mailchimp-top-bar.php)) and would love to see something like this implemented in this boilerplate, as it can truly make a difference.

PHP 5.3 is EOL in a few months so my take on it is that we as plugin authors should take an assertive stand on the matter. Especially for new plugins being written right now, I feel the only right thing to do is to benefit from PHP 5.3 features **or** at least show a notice telling users to contact their hosts.

@coenjacobs started something great with [WP update PHP](http://www.wpupdatephp.com/) as well. Worth taking a look at!

**Comment by tommcfarlin** [comment]
@danielantunes no discussion *yet* but I have started thinking about it this week. 

there's a lot of things that i'm beginning to think that the boilerplate could push in order to take advantages of new PHP standards; *however*, i don't want it to run the risk of people creating plugins that aren't compatible with certain hosts, you?

**Comment by scamartist26** [comment]
Shouldn't the boilerplate of a WordPress plugin php requirement be obvious
with the version of PHP that it's supporting platform requires? It's called
a boilerplate. WordPress states it's php requirements (to date: 5.4.2).
Tom, maybe state this? Or is this something we should all understand as
developers on the platform?

**Comment by scamartist26** [comment]
Oops, worst typo ever: 5.2.4.... Trying to get ahead of myself.

**Comment by scamartist26** [comment]
Honestly, plugins should state their requirements no matter what. Version
of WP, jquery, html, CSS, what about browsers? This is our world friends,
don't complicate it. If there is something your plugin relies on; say so.
Good point.

**Comment by mAAdhaTTah** [comment]
Also, WP-specific problem with anonymous functions: They make it really difficult for other plugin developers to unhook your filter/action functions because they don't have names.

**Comment by tommcfarlin** [comment]
> Tom, maybe state this? Or is this something we should all understand as
developers on the platform?

I think this is something that should be stated in the documentation. Thanks for the nudge!

> This is our world friends, don't complicate it 

I like this line.

> Also, WP-specific problem with anonymous functions: They make it really difficult for other plugin developers to unhook your filter/action functions because they don't have names.

Love anonymous functions in the proper context. I don't think defining them for hooks is the proper context, so I'm with you.
