### ISSUE TITLE
How should shared (admin + public) functionality be handled?

### ISSUE THREAD

**Issue by tnorthcutt** [DevinVinson/WordPress-Plugin-Boilerplate#245]
This is a subjective question, but I'm hoping someone will have input :smile:

How should functionality be added to the plugin, when it should be used in the admin and public facing parts of the plugin? For instance, right now in `class-plugin-name.php` there are the `define_admin_hooks()` and `define_public_hooks()` methods. But, what if I want to hook into more than one place and run the same code there? For instance, what if I want to enqueue the same javascript file in both places? Currently, if I do e.g.
```php
$this->loader->add_action( 'admin_enqueue_scripts', $plugin_admin, 'enqueue_scripts );
```

That will run `Plugin_Name_Admin->enqueue_scripts()` in the admin. If I want to enqueue a file in the public side, I'd need to add 
```php
$this->loader->add_action( 'wp_enqueue_scripts', $plugin_public, 'enqueue_scripts );
```
in `define_public_hooks()`, but then I'd need to duplicate code in `Plugin_Name_Public->enqueue_scripts()`. To keep things DRY, should I add a "shared" directory, class, etc.? In that case, I imagine you'd have something like this:
```php
/**
 * Register all of the hooks related to shared functionality
 * of the plugin.
 *
 * @since    1.0.0
 * @access   private
 */
private function define_shared_hooks() {
	$plugin_shared = new Plugin_Name_Shared( $this->get_plugin_name(), $this->get_version() );

	$this->loader->add_action( 'hook_location', $plugin_shared, 'shared_method' );
}
```
And then add `require_once plugin_dir_path( dirname( __FILE__ ) ) . 'public/class-plugin-name-shared.php';` to `load_dependencies()`. Is that at all reasonable? Is there another way I should be thinking about this?

**Comment by nextgenthemes** [comment]
Lets say I want to share a array between both admin and public class. Would it be best practice if I have a `get_something()` method in the main class and pass that as a 3rd argument behind, `get_version()` to the constructors of the admin and public classes where the actions are defined?

**Comment by tommcfarlin** [comment]
@nextgenthemes Keeping the class that contains the shared array would belong in the `includes` directory, and then you could either inject that class as a dependency into whatever class needs them (after which they could just call a getter on the class like you've mentioned), *or* you could setup where the result of the getter is passed as a parameter.

Depending on what all the class does would probably dictated if you want to pass the entire class or just a getter for the array.

**Comment by nextgenthemes** [comment]
@tommcfarlin Thanks, dependency class makes sense to me. I felt a bit left alone with 3.0 not so much into OOP.
