### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by nderambure** [DevinVinson/WordPress-Plugin-Boilerplate#256]
Hi, 
I think there is a typo at this line : 
https://github.com/tommcfarlin/WordPress-Plugin-Boilerplate/blob/master/plugin-name/trunk/admin/partials/plugin-name-admin-display.php#L6

It should be "admin-facing", not "public-facing".

**Comment by DevinVinson** [comment]
Fixed with https://github.com/DevinVinson/WordPress-Plugin-Boilerplate/pull/266
