### ISSUE TITLE
Best way to include Redux Framework with WPPB

### ISSUE THREAD

**Issue by gthapar** [DevinVinson/WordPress-Plugin-Boilerplate#272]
Hi,

Code - https://gist.github.com/gthapar/de054e0d276834985677

I am using the above code to include Redux Framework for plugin options page. This code is added to the main plugin file. Is there a better way to include it?

Thanks!

Best Regards,
Gautam

**Comment by DevinVinson** [comment]
The main class file in the includes folder would be a great spot since its where library type functionality is setup.

**Comment by gthapar** [comment]
I forgot I posted this but anyways thank you :)
