### ISSUE TITLE
How to add a filter?

### ISSUE THREAD

**Issue by codecowboy** [DevinVinson/WordPress-Plugin-Boilerplate#273]
I've added a filter function to my public class and added this to my main plugin class's ```define_public hooks()``` function -

```$this->loader->add_filter( 'post_link', $plugin_public ,'display_redirected_post_url');```

My function looks like this: 
```
	public function display_redirected_post_url($url, $post, $leavename) {

		if (get_post_meta( $post->ID, '_my_meta_name' ) == 'yes' ) {
			return $this->redirect_url;
		}

		return $url;

	}
```
But I'm getting two errors:

```Missing argument 2 for My_Class_name::display_redirected_post_url()
Missing argument 3 for My_Class_name::display_redirected_post_url() ```

So it seems like the arguments are not being passed to the filter. What am I missing?

**Comment by DevinVinson** [comment]
Are you adding the filter in the loader class? https://github.com/DevinVinson/WordPress-Plugin-Boilerplate/blob/master/plugin-name/trunk/includes/class-plugin-name-loader.php#L80

**Comment by fsylum** [comment]
Looks to me that you forgot to modify the accepted args for `$this->loader->add_filter`. Since your `display_redirected_post_url` function has 3 args, try

```
$this->loader->add_filter( 'post_link', $plugin_public ,'display_redirected_post_url', 10, 3);
```

**Comment by codecowboy** [comment]
Thanks @DevinVinson @fsylum  - adding the accepted args parameter solved the problem.
