### ISSUE TITLE
Unable To Add Multiple Meta boxes

### ISSUE THREAD

**Issue by gthapar** [DevinVinson/WordPress-Plugin-Boilerplate#278]
Below is the code I am using inside admin class -

```php
function register_meta_boxes()
{
    $screens = array( 'custom-post' );
    foreach ( $screens as $screen ) {
        add_meta_box(
            'prefix-1',
            __('Test 1', 'btnsx'),
            array( $this, 'callback1'),
            $screen,
            'normal',
            'high'
        );
        add_meta_box(
            'prefix-2',
            __('Test 2', 'btnsx'),
            array( $this, 'callback2'),
            $screen,
            'advanced',
            'high'
        );
        add_meta_box(
            'prefix-3',
            __('Test 3', 'btnsx'),
            array( $this, 'callback3'),
            $screen,
            'advanced',
            'high'
        );
        add_meta_box(
            'prefix-4',
            __('Test 4', 'btnsx'),
            array( $this, 'callback4'),
            $screen,
            'advanced',
            'high'
        );
        add_meta_box(
            'prefix-5',
            __('Test 5', 'btnsx'),
            array( $this, 'callback5'),
            $screen,
            'advanced',
            'high'
        );
    }
}
```

And here is the code inside admin hooks - 
```php
$this->loader->add_action( 'add_meta_boxes', $plugin_admin, 'register_meta_boxes' );
```

Problem -
Only one meta box appear for 'normal' context and only two appears for 'advanced' context on post page. How can I make all meta boxes to appear?

**Comment by Tmeister** [comment]
Well, this is not a BoilerPlate issue, the BoilerPlate only give you a base where you start coding.

Said that, I test your code in a clean install and works fine for me.

Are you testing in a clean install or do you have more plugins installed?

![00000264](https://cloud.githubusercontent.com/assets/210349/6879936/764e0658-d4db-11e4-88e1-8a0e6fec40bd.png)

**Comment by gthapar** [comment]
Hey, thank you so much!

It was an error on my part. In one of the callbacks I had a call to undefined function which caused all this issue.

Anyways thank you again.
