### ISSUE TITLE
Best practice for adding action which is called from public and admin?

### ISSUE THREAD

**Issue by datafeedr** [DevinVinson/WordPress-Plugin-Boilerplate#279]
First, congrats on inheriting WPPB! Can't wait to see where you take it.

If I have an action hook that needs to be called on every page load whether it be in the frontend or admin area, where would I make this call `$this->loader->add_action()`?

I'm trying to avoid creating a method inside both the admin and public classes.

Would you recommend creating a new method in the core plugin class like this:

```
$this->define_global_hooks(); // Call to new method
$this->define_admin_hooks();
$this->define_public_hooks();

/**
 * Register all of the hooks related to every page of the plugin.
 *
 * @since    1.0.0
 * @access   private
 */
private function define_global_hooks() {
	$plugin_global = new Plugin_Name_Admin( $this->get_plugin_name(), $this->get_version() );
	$this->loader->add_action( 'init', $plugin_global, 'do_something_on_every_page' );
}
```
Thanks,
Eric

**Comment by DevinVinson** [comment]
Yep! That is what I've done for the few instances where I absolutely need to have shared functionality.

**Comment by datafeedr** [comment]
Thanks!
