### ISSUE TITLE
How to add multiple stylesheets in admin area through function named 'enqueue_styles'

### ISSUE THREAD

**Issue by anurag-singh** [DevinVinson/WordPress-Plugin-Boilerplate#280]
Hi,

I want to add multiple style sheets in wp admin area but fails in the same. please help me out.
thanks in advance

**Comment by DevinVinson** [comment]
Can you elaborate a bit on what is failing?

**Comment by technofreaky** [comment]
@anurag-singh 
To enque multiple style sheets in wp admin you need to duplicate the below code in **admin/class-plugin-name-admin.php** on line **76**

```php
wp_enqueue_style( $this->plugin_name, 'css_file_1', array(), $this->version, 'all' );
wp_enqueue_style( $this->plugin_name, 'css_file_2', array(), $this->version, 'all' );
wp_enqueue_style( $this->plugin_name, 'css_file_3', array(), $this->version, 'all' );
```

**Comment by Tmeister** [comment]
Be aware that the handler name must be unique.

```
wp_enqueue_style( $this->plugin_name . 'css-1', 'css_file_1', array(), $this->version, 'all' );
wp_enqueue_style( $this->plugin_name . 'css-2', 'css_file_2', array(), $this->version, 'all' );
```

https://codex.wordpress.org/Function_Reference/wp_enqueue_style

**Comment by technofreaky** [comment]
@Tmeister 
Sorry.. by mistake. updated again.
Thanks

**Comment by anurag-singh** [comment]
@Tmeister & @technofreaky .... Thanks for helping me out... :-)
