### ISSUE TITLE
Making plugin main class singletone and global access to it

### ISSUE THREAD

**Issue by thc0dezer0** [DevinVinson/WordPress-Plugin-Boilerplate#283]
When I want to develop a plugin with boilerplate I encountered with some of issues, that I think these issues will be resolve by a trick. This trick is making boilerplate singletone and giving global access to it in all over the plugin code.

I think making below changes will resolve this issue.
/**

    Begins execution of the plugin. *
    Since everything within the plugin is registered via hooks,
    then kicking off the plugin from this point in the file does
    not affect the page life cycle. *

    @since 1.0.0
    */
    function run_plugin_name() {

    	return Plugin_Name::instance();

	}
$GLOBALS['plugin_name'] = run_plugin_name();

Also above changes needs some changes in class-plugin-name.php and making it singletone.

or using below implementatoin.
/**

    Begins execution of the plugin. *
    Since everything within the plugin is registered via hooks,
    then kicking off the plugin from this point in the file does
    not affect the page life cycle. *

    @since 1.0.0
    */
    function run_plugin_name() {
    	static $plugin = null;
    	if ( is_null( $plugin ) ) {
    		$plugin = new Easy_Listings_Map();
			$plugin->run();
    	}
    	return $plugin;
	}
$GLOBALS['plugin_name'] = run_plugin_name();

it seems above implementation no needs to making class-plugin-name singletone.

So when developer wants some global features it plugin he/she can put globals in this class like accessing plugin text domain.

for example when developer wants to access text domain of plugin he/she can access to it with below code.
plugin_name().get_text_domain();

what is your opinion about this idea? is there any other solution for this issue? how a developer can access global properties of plugin in boilerplate?

example issue: please note that developer wants accessing plugin dir path or plugin text domain in shortcode class so how you implement it?

I hope that I can explain my mean.

**Comment by nathanmarks** [comment]
Hey @thc0dezer0, the previous version of the boilerplate did implement a singleton pattern. I think Tom answered this question best [here](https://github.com/DevinVinson/WordPress-Plugin-Boilerplate/pull/228):

> The Singleton Pattern is something that I used to use in the previous version of the Boilerplate, but have since moved away from it primarily because it can be viewed as an anti-pattern (that is, why go object-oriented if you're only going to restrict part of the code to a single instance).
>
> There are other strategies for achieving the same thing.
>
> Regardless, the Singleton Pattern can still be implemented by providing a wrapper around the core plugin class and handling it from there. It's not something I'm necessarily against doing, but it's not something I want to fold into the core of the Boilerplate.

**Comment by jjeaton** [comment]
@nathanmarks this isn't directed at you specifically, just a general comment :smile: 

This question comes up about every month or so on this repo, and the answer each time references:

> There are other strategies for achieving the same thing.

Which, while it's true, isn't very helpful for developers trying to learn how to build a plugin from the boilerplate. Being able to access and modify the plugin's hooks from another plugin is generally very useful for extendability, and many popular (and well-coded) plugins do that today with a singleton (EDD and bbPress to name a few)

If the boilerplate isn't going to use the singleton pattern (yay!) ideally there would be a better answer to this question than "there's many ways to do it, but don't use a singleton". Whether that's an official DI container or other plugin wrapper, this question could go away if there's some example code to point to and say "this is a **best practice** way to achieve what you want".

**Comment by thc0dezer0** [comment]
I think this plugin should has a Dependency Injection Container, because it can resolve most problems as @jjeaton said.

**Comment by DevinVinson** [comment]
Keep in mind that the boilerplate isn't a one-stop option for the most advanced plugin boilerplate. We are trying to keep things in line with how WordPress is working and following its best practices.

For the short term, it means I will wait and see how core handles dependencies rather than try and pave the way.
