### ISSUE TITLE
wppb generator

### ISSUE THREAD

**Issue by 4selin** [DevinVinson/WordPress-Plugin-Boilerplate#284]
Hello!
It takes a lot of time to rename files, classes etc from "plugin_name" to "my_super_new_plugin".
It would be great to fill a form with new plugin name and click button "generate".

**Comment by slushman** [comment]
Try the one at http://wppb.me :)

**Comment by skmohammadi** [comment]
It was better if all plugin_name and other alts. be covered by wbpb.me
