### ISSUE TITLE
How can I avoid God objects in this boilerplate?

### ISSUE THREAD

**Issue by wsenjer** [DevinVinson/WordPress-Plugin-Boilerplate#285]
Hello Devin, 
Thank you for this effort. 

I have a question, according to the boilerplate, I should add all my code in the main class inside `class-plugin-name.php` I think this will lead to a God object when the plugin code gets bigger. 

Any thoughts?

**Comment by nathanmarks** [comment]
Hey @wsenjer, I think you may have misinterpreted the comments in `class-plugin-name.php`. That file is merely a "conductor" of sorts where you defined your hooks, initialize/run the loader and setup internationalization. Your plugin code should be distributed throughout files in the public/admin directories. How you structure that is up to you -- the boilerplate leaves quite a bit of flexibility in that regard and it is possible to implement several different design patterns from there.

**Comment by DevinVinson** [comment]
Good explanation @nathanmarks . The plugin is a starting point and not the only files you can have.
