### ISSUE TITLE
How to properly handle the plugin text domain

### ISSUE THREAD

**Issue by fusillicode** [DevinVinson/WordPress-Plugin-Boilerplate#286]
Hi Devin :)

I'm facing the need to use the plugin text domain to localize many different strings in its admin section but I'm not sure if I'm doing it correctly. 

I'm using the id of the plugin passed to the admin section (i.e. my-plugin-admin.php). The problem is that the admin section uses a custom WP List (i.e. an extension of the core WP_List_Table) in which I still have the need to access the text domain. 

What I'm doing right now is to pass to the WP_List_Table the instance of the admin section and access a property text domain that I've created in the admin section itself. This property is instantiated with the over mentioned plugin id.

Is this the right approach or should I handle this situation differently? I'm thinking about the my-plugin-i18n.php boilerplate?

I hope I was clear :(

Sorry for the bother and thank you for your effort :)

Cheers!

**Comment by Tmeister** [comment]
The best practices dictated that you shouldn't use variables as your text-domain string, you should use plain text.

`__("Your String", "your-text-domain");`

Let me quote why.

> The reason you never do this is because translation relies on looking up strings in a table and then  translating them. However, that list of strings to be translated is built by an automated process. Some code scans your PHP code, without executing it, and pulls out all the __()’s it finds, then builds the list of strings to be translated. That scanning code cannot possibly know what is inside $string.

Here is the full post about it. http://ottopress.com/2012/internationalization-youre-probably-doing-it-wrong

**Comment by fusillicode** [comment]
Thank you a lot Enrique! Your explanation was clear and concise. 

Besides that I think that the article you've linked should be put right inside the codex!

Thank you again! 

Cheers!
