### ISSUE TITLE
Minimum PHP version

### ISSUE THREAD

**Issue by codecowboy** [DevinVinson/WordPress-Plugin-Boilerplate#287]
Is there anything in the codebase which would not work on PHP 5.3.28 that you are aware of? I am aware that this is no longer supported and that WordPress.org recommends 5.4+ but clients will be clients ;)

**Comment by mAAdhaTTah** [comment]
Up to this point, the Boilerplate has aimed to conform with Wordpress standards, so it supports whatever WordPress supports.

**Comment by DevinVinson** [comment]
Yep, everything should run fine there.
