### ISSUE TITLE
plugins built with this boilerplate?

### ISSUE THREAD

**Issue by fbm-static** [DevinVinson/WordPress-Plugin-Boilerplate#289]
It would be nice how others have used this boilerplate and how they have added their own functions from this point.

**Comment by rydzyk** [comment]
I had the same problem  

just paste: 
site:wordpress.org/plugins/ Plugin Boilerplate 
to Google :P

**Comment by DevinVinson** [comment]
I'm working on gathering a list of them for that very reason @fbm-static .

If you have any send them on over.

**Comment by goranefbl** [comment]
Found one with good ratings: 

https://wordpress.org/plugins/beautiful-taxonomy-filters/

**Comment by goranefbl** [comment]
He created separate php file for each of settings field callback, would that be best practices?

**Comment by DevinVinson** [comment]
If anyone finds or writes any others I added a page in the wiki for them: https://github.com/DevinVinson/WordPress-Plugin-Boilerplate/wiki/Example-Plugins
