### ISSUE TITLE
Custom Post Type Modularization in Sub-Folders

### ISSUE THREAD

**Issue by robsn** [DevinVinson/WordPress-Plugin-Boilerplate#291]
According to [#261](https://github.com/DevinVinson/WordPress-Plugin-Boilerplate/issues/261) the "correct" way to register custom post types is via loader.

> In the class-plugin-name.php file, in define_admin_hooks(), put something like:

>        $this->loader->add_action( 'init', $plugin_admin, 'create_custom_post_type' );

> Move your create_custom_post_type() function into the class-plugin-name-admin.php file in the admin folder. That should do it.

I was wondering how one could achieve modularization/encapsulation of different custom post types / functionalities to not "pollute" the ```class-plugin-admin.php``.

Let's say there're 3 different custom post types (e.g. Slider, Portfolio, Testimonials). If you now create 3 different classes for them in sub-folders where would you put them? In the ```/admin``` or ```/include```.

**Approach**
+ includes/
    + slider/
        + partials/
        - class-slider.php
    + portfolio/
        + partials/
        - class-portfolio.php
    + testimonials/
        + partials/
        - class-testimonials.php
    - class-plugin.php
    - class-plugin-loader.php

Would you instantiate the classes in ```load_dependencies()```at ```class-plugin.php``` or what would be your approach to load the functionality?

Would you set up additional private functions e.g. ```define_custom_post_type_hooks()``` or call the hooks of the 3 new classes via ```define_admin_hooks```?

Any help is highly appreciated.

**Comment by DevinVinson** [comment]
If you wanted to go with a modular approach then I would consider them includes territory. Then add each as a dependency.

**Comment by grantpalin** [comment]
Following from this, I've got a current pattern set up. In `class-pluginname.php`:

    private function load_dependencies() {
        // ...
        require_once plugin_dir_path( dirname( __FILE__ ) ) . 'includes/post_types/class-pluginname-post-types.php';
    }

...

    private function define_admin_hooks() {
        // ...
        $post_types = new PluginName_Post_Types();
        $this->loader->add_action( 'init', $post_types, 'load' );
    }

  And in the new orchestrating class:

    class PluginName_Post_Types {
        public function load() {
            require_once 'class-pluginname-cpt-name.php';
            $cpt = new CAES_CPT_Name();
            $cpt->create_post_type();
        }
    }

This way, custom types need be managed in only one place. So far this setup is working for me, admittedly for just one custom type, but I'm doing similarly for a custom taxonomy.

**Comment by DevinVinson** [comment]
I like that approach @grantpalin. Do you have a full example I can point to in the wiki?

**Comment by robsn** [comment]
@grantpalin Nice Approach, I ll give it a try. Thank you
