### ISSUE TITLE
Create Custom Post Types, But Where?

### ISSUE THREAD

**Issue by lazharichir** [DevinVinson/WordPress-Plugin-Boilerplate#294]
Hi guys,

Very very new to OOP so getting extremely confused here. I have built a plugin that I used just for myself but I am planning on making it available soon, however, it is not very readable right now, hence why converting it into an OOP with this Boilerplate.

However, the basic thing I need, which is to create my multiple CPTs seems like a hurdle already. I believe this code should go in the admin/ folder and in the admin class file. But where do I call the instantiation of the CPT?

Thank you :)

**Comment by goranefbl** [comment]
I know its closed but for future pps, check how its done here https://github.com/slushman/now-hiring
