### ISSUE TITLE
Please confirm video tutorial acceptable

### ISSUE THREAD

**Issue by lindsaymacvean** [DevinVinson/WordPress-Plugin-Boilerplate#299]
Hi there im only an intermediate coder, I have been messing around with the the boilerplate this afternoon and did a quick tutorial to help others get started using the new 3.0. Can someone who has more experience with oop and this boilerplate give it a quick watch and see if I have broken any golden rules. It is approx 5mins.

If it is helpful for newbies I can do some more like it.

https://www.youtube.com/watch?v=uyfJ1VDU81I&feature=youtu.be

**Comment by DevinVinson** [comment]
Hey!

Looks good. A bit scattered but it feels genuine and offers at least a very basic introduction to what you've done.

Just make sure if you do anymore to note that Tom has handed the project off so that he doesn't keep getting mail/tweets about it :smile:

**Comment by DevinVinson** [comment]
Feel free to add your video and a short description here: https://github.com/DevinVinson/WordPress-Plugin-Boilerplate/wiki/Public-Resources
