### ISSUE TITLE
Question on using pluginname-admin-display.php in /admin/partials

### ISSUE THREAD

**Issue by erayit** [DevinVinson/WordPress-Plugin-Boilerplate#300]
I have wired up a custom admin menu by adding a function to class-pluginname-admin.php (see below) and then wired up my add_menu action by adding it to the define_admin_hooks()  function in class-pluginname.php.  The boilerplate is really nice... anyway.  

I have my menu create using the following:

add_menu_page(
'Name here',
'Name here'
'administrator',
'cta_admin_menu',
array($this,'custom_menu_function')
);

If I add the "custom_menu_function" to this same class-pluginname-admin.php file it will work as expected.  But reviewing the comments in the BoilerPlate it would seem that my menu callback function should be placed in /admin/partials/pluginname-admin-display.php.  However, if I place my "custom_menu_function" there I cannot not call it (with or without the class reference).  

I was able to overcome this issue by adding the /admin/partials/pluginname-admin-display.php to the load_dependencies function like this:

 /**
* The class responsible for defining all views that occur in the admin area.
*/
require_once plugin_dir_path( dirname( __FILE__ ) ) . 'admin/partials/pluginname-admin-display.php';

I would really like to stay within the intended guidelines of the BoilerPlate and good coding practices.  

Have I made a mistake in just adding the pluginname-admin-display.php to the dependencies list? 

Is there another way to call a function in that pluginname-admin-display.php file?  I assumed that all my admin page html should be there but I need to able to reference it from the menu... thoughts?

Thank you

**Comment by erayit** [comment]
Update - I found some other references that used the function locally in class-pluginname-admin.php (with a class callback).  In the local callback function they have a require_once to pull in the /admin/partials/pluginname-admin-display.php rather than having it in the dependencies list as I suggested earlier. This seems like a better way as it keeps functions out of the pluginname-admin-display.php leaving only php and html but I would like some feedback on "best practices" for this.  Thank you

**Comment by codesman** [comment]
> Have I made a mistake in just adding the pluginname-admin-display.php to the dependencies list?

> Is there another way to call a function in that pluginname-admin-display.php file? I assumed that all my > admin page html should be there but I need to able to reference it from the menu... thoughts?

I've been working through this myself and although I can't speak for the author, I would suggest that perhaps you have made a mistake.  Or to phrase it better, not yet found the best way to do it!  :)

The add_menu_page() function is meant to be used in a hook, specifically the 'admin_menu' hook. You use the plugin's Loader class to do this.

Not sure if this is best practice or not but this is how I did it. Seems pretty clean.

The first step is to define your hook in the define_admin_hooks() of the plugin-name/class-plugin-name.php. It would look something like this:

	/**
	 * Register all of the hooks related to the dashboard functionality
	 * of the plugin.
	 *
	 * @since    1.0.0
	 * @access   private
	 */
	private function define_admin_hooks() {

		$plugin_admin = new Plugin_Name_Admin( $this->get_plugin_name(), $this->get_version() );

		$this->loader->add_action( 'admin_enqueue_scripts', $plugin_admin, 'enqueue_styles' );
		$this->loader->add_action( 'admin_enqueue_scripts', $plugin_admin, 'enqueue_scripts' );

        // Hooks into admin_menu hook to add custom page
		$this->loader->add_action( 'admin_menu', $plugin_admin, 'add_admin_page' );
	}

Then, in the file plugin-name/admin/class-plugin-name.php you would add 2 functions, one to add the menu page and the other to load the plugin page partial, like this:

    // Create the Plugin Name menu page with add_menu_page();
    public function add_admin_page() {
		add_menu_page(
			'Plugin Menu Name',
			'Plugin Page Title',
			'manage_options',
			$this->plugin_name,
			array( $this, 'load_admin_page_content' ), // Calls function to require the partial
			plugins_url( 'plugin-name/images/icon.png' ),
			6
		);
	}

    // Load the plugin admin page partial.
	public function load_admin_page_content() {
		require_once plugin_dir_path( __FILE__ ). 'partials/plugin-name-admin-display.php';
	}

**Comment by slushman** [comment]
I've been doing this:

public function options_page() {
	?><h2><?php echo esc_html( get_admin_page_title() ); ?></h2>
		<form method="post" action="options.php"><?php
		settings_fields( 'now_hiring_options' );
		do_settings_sections( $this->plugin_name );
		submit_button( 'Save Settings' );
	?></form><?php
}

You could also put all that stuff in the middle in a partials file like Tom shows above.

**Comment by erayit** [comment]
Thanks to codesman and slushman for the replies, I appreciate your time.  I really like codesman's suggestion to only pull the file in if the menu item is clicked rather than when the plugin is loaded.  This method will also allow me to keep all my functions in the class and only pull in the display page(s) as needed.

Thanks again!

**Comment by Qwarble** [comment]
codesman, thanks a lot! You've saved my time!

**Comment by thekingf4** [comment]
codesman, thanks !! You are very Good Developer
