### ISSUE TITLE
How to write a plugin for wp-login.php using this boilerplate?

### ISSUE THREAD

**Issue by pingram3541** [DevinVinson/WordPress-Plugin-Boilerplate#302]
I'm still unclear on how admin and public is differentiated in this boilerplate.  I cannot find a single instance of is_admin but when I change the default hooks inside the main class there does seem to be some logic where the plugin IS aware of whether I am on the front end or the back end.

For example, if I change this inside define_admin_hooks in /includes/class-myplugin.php:

    $this->loader->add_action( 'admin_enqueue_scripts', $plugin_admin, 'enqueue_styles' );

to:

    $this->loader->add_action( 'login_enqueue_scripts', $plugin_admin, 'enqueue_styles' );

It still does not load on wp-login.php like I expected, how does the plugin know I am not in the admin area???

But when I change this inside the define_public_hooks in /includes/class-myplugin.php:

    $this->loader->add_action( 'wp_enqueue_scripts', $plugin_public, 'enqueue_styles' );
    //which I also wonder why it is not wp_enqueue_styles instead

to:

    $this->loader->add_action( 'login_enqueue_scripts', $plugin_public, 'enqueue_styles' );

It does load the stylesheet in wp-login.php

Where is the logic.  Is it something I have not learned yet in a built in naming convention?  Such as where WP resolves something_admin vs something_public?

**Comment by pingram3541** [comment]
I see now that public and admin in this boilerplate truly has no real control as to what is loaded on the front or back end and that the actual $hook itself is really what matters here.  For scripts and styles I could choose either the admin or public areas to provide the action 'login_enqueue_scripts' which also explains why neither of the defaults worked.

**Comment by DevinVinson** [comment]
The boilerplate doesn't really do anything. Its a model to help *you* do something.

So if you change the admin css hook to output on login_enqueue_script then that is where it will show.
