### ISSUE TITLE
Variables as text-domain - Internationalization

### ISSUE THREAD

**Issue by EvanHerman** [DevinVinson/WordPress-Plugin-Boilerplate#303]
Hi,

I've used this boilerplate in the past for some of my plugins. I've recently come across an interesting article written by Mark Jaquith, stating that  you shouldn't be passing in text-domains via variables. You can find the article here : https://markjaquith.wordpress.com/2011/10/06/translating-wordpress-plugins-and-themes-dont-get-clever/

You can see some discussion going on in the comments, but it doesn't appear that there ever was a definitive answer on the proper way.

Otto has also written about it in his article:
http://ottopress.com/2012/internationalization-youre-probably-doing-it-wrong/

Otto also states that this method for text-domains does not conform to WordPress coding standards and is technically a bug within the plugin itself.
http://ottopress.com/2012/internationalization-youre-probably-doing-it-wrong/#div-comment-10588

In the readme of this plugin boilerplate it states: 

>**i18n Tools**
The WordPress Plugin Boilerplate uses a variable to store the text domain used when internationalizing strings throughout the Boilerplate.

I'm wondering if this is not the correct way to be handling localization/internationalization within the plugin and would love to hear some input.

Thanks,
Evan

**Comment by slushman** [comment]
Jaquith is right, if you want something translatable, you'll need to use the text-domain string in the translate function rather than a variable.

GOOD:
__( 'String to translate', 'my-plugin' );

BAD:
__( 'String to translate', $this->plugin_name );
__( 'String to translate', PLUGIN_NAME_CONSTANT );

Since I read a similar article by Samuel Wood (http://ottopress.com/2012/internationalization-youre-probably-doing-it-wrong/) I've changed my i18n process. I only use the $plugin_name variable for things like naming scripts and stylesheets in the enqueue function or some other place where the name of the plugin is handy to use, but not for translation functions.

**Comment by jjeaton** [comment]
+1 to not using a variable for text domains.

**Comment by AlchemyUnited** [comment]
Not to get #OffTopic and perhaps this is the wrong forum / moment (but maybe it is)., is that word for work translation might not always yield the best UI / UX. It's very possible a given user / client has a particular lexicon that might not fit nicely within some translation to Language X. 

My point being, and again perhaps this isn't the right time, etc, it would be nice to see the boilerplate architecture address this disconnect. 

if it helps, for my own classes the strings / labels (?) are usually in an associative array. That way it's ez for someone else (forking on GH) - or even myself from project to project - to just change those values without getting into an i18n  translation dust up. 

So...What if plugin classes were "plugable" and all the strings / labels and such were centralized within a single class within plugin? Or if not plugable, what if there was a filter for filtering the strings class? Those could still be i18n'ed but also adjusted if necessary.

I hope this makes sense.

**Comment by slushman** [comment]
If I'm understanding you correctly, all the strings are in a centralized file that can be edited and then displayed throughout the plugin? In that case, when you put them unto the array, you'd do the translation function the same as above:

$buttons = array(
'button1' => __( 'Label for Button 1', 'my-plugin' ),
'button2' => __( 'Label for Button 2, 'my-plugin' )
);

etc. Anyone forking the project would only need to update the strings in that one file. I don't see why that wouldn't work since the text-domain is still a string. Or am I not understanding correctly?

**Comment by EvanHerman** [comment]
I had a feeling, but this topic doesn't seem to receive much attention. When I started out as a plugin dev I often looked into others plugins/code and saw the text-domains being passed in as variables/constants which is why, I too, began to use the same method.

After seeing the above articles, I've since learned that I've been doing it wrong all along and so have many other developers.

I guess since my thoughts were confirmed, the plugin boilerplate should be updated to use hardcoded strings instead of variable names as it currently does so we can conform to best practices and WP code standards. I did take a look at the current code up in the repo and it doesn't appear to be using the text-domain variables anymore like the readme states. I remember in older versions of the plugin boilerplate the text-domain was used in the base, but I guess that's since been removed.

Either way, good to confirm my thoughts on properly defining the text-domain inside the internationalization functions.


Thanks for the input guys!

**Comment by AlchemyUnited** [comment]
@slushman yeah, that's about it :) the main idea being these strings aren't really strings but values, as in options. and some might want to use a different value for a given option. 

but i'd also like to suggest a filter as well. if only to allow a dev to tweak a string option with minimal effort. 

i18n works, obviously, in a pre OOP sorta way, but it's kinda a blunt instrument. it would be nice to see a standard that has flexibility baked in. The centralization is also, imo, a nice benefit.

**Comment by grappler** [comment]
+1  for switching to strings.

Extra bit of information: https://ulrich.pogson.ch/string-text-domain-must

Related: https://github.com/DevinVinson/WordPress-Plugin-Boilerplate/issues/165 https://github.com/DevinVinson/WordPress-Plugin-Boilerplate/issues/59

**Comment by DevinVinson** [comment]
Definitely a todo here. I read your comment from some time ago on the same issue @EvanHerman so thank you for bringing it back up.

**Comment by DevinVinson** [comment]
I just published a branch to finally finally address this. I don't think anything else is needed so if anyone wants to put eyes on it before I merge :+1:

**Comment by grappler** [comment]
It looks good as there are no strings in the plugin to internationalize.
