### ISSUE TITLE
include for wp_footer not working.

### ISSUE THREAD

**Issue by goranefbl** [DevinVinson/WordPress-Plugin-Boilerplate#306]
I am creating a plugin that is displaying some sticky bar at the bottom of every page. So I have this inside public hooks:
`
$this->loader->add_action( 'wp_footer', $plugin_public, 'front_end' );
`
and my function looks like this:
```
public function front_end($content) {
		echo 'test';
		ob_start();
		include plugin_dir_path( dirname( __FILE__ ) ) . 'public/partials/wp-rating-public-display.php';
		$content .= ob_get_contents();
		ob_end_clean();
		return $content;
	}
```
The issue is that anything that is included inside this file that i am including does not get displayed, while its displaying if i for example use the_content filter instead of wp_footer action. It does display if code is directly in function, but i want to have html code in separate file.

Again file exists and its showing just fine if i add it through the_content filter, but wp_footer isnt.

**Comment by DevinVinson** [comment]
Try doing a simple include_once relative to that partial.

**Comment by goranefbl** [comment]
Hi Devin,

doing include without buffer output works. If i just add html content inside that document and include it without buffer output, would that be best practices, how do you add front end html through functions if you want to keep it out of main public class?

Again thanks for your response.

**Comment by DevinVinson** [comment]
Sorry for the delayed response. I don't know the answer to that one. Including like that is how I've always seen it done and if there is a downside to it I'm not familiar with it.

**Comment by goranefbl** [comment]
Thanks Devin.

**Comment by goranefbl** [comment]
My plugin is fully done https://wordpress.org/plugins/swifty-bar/ thanks for your assistance Devin! Helped alot to keep it within best practices.

**Comment by jarfer** [comment]
Hi all,

I hit this problem today, passing 'wp_footer' (when calling add_action(...) with your inline code does not work with (the latest) vanilla Wordpress at the time of writing. Consider the following code:


function footer_script(){ ?>
<script>
jQuery(document).ready(function(){
    //put your js code here
})
</script>
<?php }
add_action('wp_footer', 'footer_script'); ?>

This jQuery ready callback appears exactly when called NOT in the footer as the documentation states. 

Unless it depends on something I have wrong? I've seen many people give examples of this, so far none work from what I can tell.
