### ISSUE TITLE
Working Samples?

### ISSUE THREAD

**Issue by devcon7** [DevinVinson/WordPress-Plugin-Boilerplate#307]
Hello,

I am trying to create the admin panel following the boilerplate's guide, but kind of lost.

I want to use the ch-reservation-admin-display.php to display the content for the admin side.

I created a public function in class-ch-reservation-admin.php

but, now I am confused where to put the action to load the function I created in the class-ch-reservation-admin.php .

Or.. is this a totally a wrong approach?

There is an article I found (http://tangrufus.com/wordpress-plugin-boilerplate-tutorial-getting-started/), but it seems like it is using the older version and it doesn't work.

Any help will be appreciated!

Thank you.

**Comment by slushman** [comment]
All the actions and filters are declared in the includes > class-your-plugin-name.php file. In this case, you'd add it in the admin_hooks function. Copy the action for the scripts and replace the appropriate function names and hook name.

**Comment by devcon7** [comment]
Thank you Slushman.

However, I am not following thing right.. 

in the includes\class-your-plugin-namep.php, I see the following:
===================================================
private function define_admin_hooks() {

		$plugin_admin = new CH_Reservation_Admin( $this->get_plugin_name(), $this->get_version() );

		$this->loader->add_action( 'admin_enqueue_scripts', $plugin_admin, 'enqueue_styles' );
		$this->loader->add_action( 'admin_enqueue_scripts', $plugin_admin, 'enqueue_scripts' );

// ADD ACTION HERE?
                add_action('admin_menu', 'my_custom_menu); 

	}

// THEN PUT THE FOLLOWING FUNCTION IN THE SAME FILE?
public function my_custom_menu(){
	add_menu_page(
		'My Custom Plugin Settings', 
		'Custom Plugin', 
		'activate_plugins', 
		'custom-plugin-main', 
		'get_admin_content', 
		'', 
		100
	);
}

public function get_admin_content(){
	include_once(plugin_dir_url( __FILE__ ) . 'admin/partials/plugin-name-admin-display.php');
}
===================================================

Also, on the side note, may I get your help understanding the follwing action hook?
add_action( 'admin_enqueue_scripts', $plugin_admin, 'enqueue_styles' );

I thought the parameters are limited to:
add_action( $tag, $callback_function, $priority, $accepted_args )

but the add_action contains the $tag, OBJECT, then.. 'enqueue_styles'???
Got lost here..

Thank you!

**Comment by slushman** [comment]
Sorry, poor explanation on my part.

In the class-ch-reservation.php file, in the define_admin_hooks function, you would put something like:
```
add_action('admin_menu', $plugin_admin, 'my_custom_menu);
```
Then put the my_custom_menu function and all the other settings functions in the class-ch-reservation-admin.php file. 

In version 3 of the boilerplate, the loader class handles interpreting these custom add_action calls into the standard WordPress calls. Its sort of confusing at first, but once you get used it, it makes sense. The boilerplate's add_action takes an extra augment: the class object where your function for the action or filter resides. In the code above, we're hooking the my_custom_menu function in the $plugin_admin instance of the admin class to the WordPress hook "admin_menu". Make sense?

To add additional actions and filters, just follow the same pattern as above and referencing the corresponding function in the corresponding class. You can check out my "Now Hiring" plugin to see how I put it all together. The Wiki on here also has a few other plugins that show how it all works.

**Comment by devcon7** [comment]
Pretty amazing!

Now it starts making sense.. this is a very nice.
