### ISSUE TITLE
Shortcode

### ISSUE THREAD

**Issue by devcon7** [DevinVinson/WordPress-Plugin-Boilerplate#310]
Using a shortcode display the contents in plugin-name-public-display.php, what is the recommended way?

Should I use "include" or capture output buffer and return?

Please advise.

**Comment by devcon7** [comment]
"include" method doesn't seem to be the best choice.

ob_start(); 
 "call the content"
return ob_get_clean(); 

seems a better solution.

However, what is the proper way of putting add_shortcode('my-shortcode', 'show-public-display');?

I've added the public function show-public-display(){} in the public/class-plugin-name-public.php and put the add_shortcode in the include/class-plugin-name.php under private function define_public_hooks().

Please advise!!

**Comment by slushman** [comment]
I've used both successfully. I always use a buffer then put all the HTML in an included file. I'd highly advise checking out the plugins on the Wiki page to see how others are already doing this.

As far as adding shortcodes, I've seen two different ways. Devin said he adds a shortcode registration function to the loader class and declares them from the define_hooks function in the main plugin class. Look through the other issues for shortcodes to find his explanation.

I put a "register_shortcodes" function in the public class, then do all the add_shortcode declarations in there. You can add all the shortcodes at once this way and its only one hook to define in the define_hooks function. Check out my Now Hiring plugin here on Github to see specifics.

**Comment by devcon7** [comment]
Got it! Had no luck using the loader method, but in the functions, it is working now.

I wish there is a forum to handle these topics. Wikipage has some good resources, but most of them are for the previous version and has bug..... 

I really appreciate your prompt help!
