### ISSUE TITLE
Settings Field Default Value

### ISSUE THREAD

**Issue by devcon7** [DevinVinson/WordPress-Plugin-Boilerplate#316]
Hello,

I am trying to locate a documentation, but I am not able to find a good one.

I am trying to assign a default value for the options registered, but not sure about the best practice.

Basically, adding a checkbox to the admin menu section, but not sure where to run the function to set the default value of the checkbox. 

Do I put this in the activator.php? or just the class-pluginname-admin.php?

Setting up the default value should only fire when the plugin is installed.

Thank you!

**Comment by DevinVinson** [comment]
Funny enough I just did the demo settings part of the new demo plugin/example I'm working on. 

Let me see if I can get the work-in-progress online for you to look at a bit early.

**Comment by devcon7** [comment]
I'm very excited! Please let me know when it becomes available.

Thank you!!

**Comment by DevinVinson** [comment]
Okay, threw the class up in a gist for you: https://gist.github.com/DevinVinson/0491551cdd35d7935030

Right now I just have that set as a dependency to my admin class. All the add_actions are still handled in the includes class plugin file. This was out of convenience so I'm not sure if this is the *best* method for brining the pieces together but it works and has a bit of temporary output you can play with.

So in my class-wppb-demo-plugin-admin.php I added:
```
/**
	 * Load the required dependencies for the Admin facing functionality.
	 *
	 * Include the following files that make up the plugin:
	 *
	 * - Wppb_Demo_Plugin_Admin_Settings. Registers the admin settings and page.
	 *
	 *
	 * @since    1.0.0
	 * @access   private
	 */
	private function load_dependencies() {

		/**
		 * The class responsible for orchestrating the actions and filters of the
		 * core plugin.
		 */
		require_once plugin_dir_path( dirname( __FILE__ ) ) .  'admin/class-wppb-demo-plugin-settings.php';

	}
```
Then in class-wppb-demo-plugin.php:
```
/**
	 * Register all of the hooks related to the admin area functionality
	 * of the plugin.
	 *
	 * @since    1.0.0
	 * @access   private
	 */
	private function define_admin_hooks() {

		$plugin_admin = new Wppb_Demo_Plugin_Admin( $this->get_plugin_name(), $this->get_version() );
		$plugin_settings = new Wppb_Demo_Admin_Settings( $this->get_plugin_name(), $this->get_version() );

		$this->loader->add_action( 'admin_enqueue_scripts', $plugin_admin, 'enqueue_styles' );
		$this->loader->add_action( 'admin_enqueue_scripts', $plugin_admin, 'enqueue_scripts' );

		$this->loader->add_action( 'admin_menu', $plugin_settings, 'setup_plugin_options_menu' );
		$this->loader->add_action( 'admin_init', $plugin_settings, 'initialize_display_options' );
		$this->loader->add_action( 'admin_init', $plugin_settings, 'initialize_social_options' );
		$this->loader->add_action( 'admin_init', $plugin_settings, 'initialize_input_examples' );

	}
```
