### ISSUE TITLE
Understanding plugin structure

### ISSUE THREAD

**Issue by teastudio** [DevinVinson/WordPress-Plugin-Boilerplate#325]
Hi, I am trying to understand the Plugin Boilerplate structure of folders and some classes and I have a few questions:
1. in "plugin-name/plugin-name.php" file you run "activation/deactivation" functions by "register_activation_hook". Why not in "__construct" method from "includes/class-plugin-name.php"?
2. why are you using always static methods in classes?
3. where should I register post_type, in "class-plugin-name-activator.php" or by call "init" action added into "define_admin_hooks"  ?

thanks for explaining this.

**Comment by DevinVinson** [comment]
The boilerplate attempts to follow best practices and WordPress standards. So for 
1 and 2) https://developer.wordpress.org/plugins/the-basics/activation-deactivation-hooks/

3) In the admin hooks could definitely work. There is a bit more flexibility in where you do things based on how your plugin will work so I'm not super opinionated on that personally.

**Comment by teastudio** [comment]
ok, I have another question:
in includes/class-plugin-name.php you has the loader object and define_admin_hooks function:

```php
...
	private function define_admin_hooks() {
		$plugin_admin = new Plugin_Name_Admin();
        $plugin_post_type = new Plugin_Name_Post_Types( $this->loader );

		$this->loader->add_action( "admin_enqueue_scripts", $plugin_admin, "enqueue_styles" );
		$this->loader->add_action( "admin_enqueue_scripts", $plugin_admin, "enqueue_script", 100 
);
...
}
```


so, in/to Plugin_Name_Post_Types class should I:
1) transfer loader object as above
or
2) create new loader object?

Which version is correct?

**Comment by DevinVinson** [comment]
If you are including the loader into your Plugin_Name_Post_Types then you would do it just like in the main plugin class (class-plugin-name) above.

This plugin shows an example of creating the custom post type inside of the admin class and then adding the function into the loader at init https://github.com/slushman/now-hiring

Maybe that will help clear things up?

**Comment by teastudio** [comment]
sorry, but no. It not helped me, more I think it's wrong, because one class does the whole job (add actions and filters, create pos type, save objects, prepare lists, etc...)
I think they should create separate files for each object. Am I wrong?

**Comment by slushman** [comment]
If you wanted to create a separate class for creating a custom post type, try this:

Include the file in load_dependences in the plugin class, then create another "hooks" method where you'd then put your add_action call. 

`private function my_cpt_hooks() {
$my_cpt = new My_CPT_Class( $this->get_plugin_name(), $this->get_version() );
add_action( 'init', $my_cpt, 'cpt_creation_method' );
}`

Then call my_cpt_hooks() in the constructor of the plugin class. That would take the CPT creation methods out of the admin class and keep all the actions and filters in the plugin class. I've done that with a few things, just testing it out, and it works nicely.

**Comment by teastudio** [comment]
that's the idea! thanks

**Comment by slushman** [comment]
Bonus tip:

In your custom CPT class, make the method creating the custom post type static. Then include it in the activation method in the activation class, statically call the CPT creation method, then call flush_rewrites(). This way, when the plugin is activated, you won't get 404s for the new CPT pages on the front-end. From Now Hiring:

`public static function activate() {

	require_once plugin_dir_path( dirname( __FILE__ ) ) . 'admin/class-now-hiring-admin.php';

	Now_Hiring_Admin::new_cpt_jobs();
	Now_Hiring_Admin::new_taxonomy_type();

	flush_rewrite_rules();

}`

The down side of using a separate class for this is the static method call requires everything to be in that method. If you're calling any class variables, the static method will throw errors. Ultimately, this is why I stuck with creating the CPTs in the admin class rather than creating a separate class.

**Comment by teastudio** [comment]
yeap, and I do that in my post: https://github.com/DevinVinson/WordPress-Plugin-Boilerplate/issues/325#issuecomment-135502019

**Comment by mahfoodh** [comment]
Hi Vinson,
Great efforts I am currently using your boilerplate and created a plugin for CPT as well as Metaboxes, Custom Taxonomies and Taxonomy Custom Fields. I was wondering what is the best way to enable the creation of multiple CPTs, Taxonomies and Metaboxes.
I had to resort to creating additonal classes for each of the mentioned objects to enable multiple instances. Then I used a function within the main admin class to call the intended classes. I have also created private members of type multi-dimention arrays in the main admin class to store custom post types and metaboxes as well as custom taxonomines settings.
In addition I have embded CMB2 and Redux Framework with my plugin. So far things things are pretty good.

Regards,
Mahfoodh

**Comment by DevinVinson** [comment]
Beyond the base boilerplate code, how you build out the rest of your plugin is up to you. 

Sounds like you have a pretty good setup so far!

**Comment by ramzep** [comment]
> Hi Vinson,
> Great efforts I am currently using your boilerplate and created a plugin for CPT as well as Metaboxes, Custom Taxonomies and Taxonomy Custom Fields. I was wondering what is the best way to enable the creation of multiple CPTs, Taxonomies and Metaboxes.
> I had to resort to creating additonal classes for each of the mentioned objects to enable multiple instances. Then I used a function within the main admin class to call the intended classes. I have also created private members of type multi-dimention arrays in the main admin class to store custom post types and metaboxes as well as custom taxonomines settings.
> In addition I have embded CMB2 and Redux Framework with my plugin. So far things things are pretty good.
> 
> Regards,
> Mahfoodh

       Hello Mahfoodh,Devin,
            I have problem with the boilerplate and CMB2, can you please advise me. I have a javascript error
TypeError: jQuery(...).innerFade is not a function

Can you please share the way to integrate it.
than,s
