### ISSUE TITLE
How do you properly add_shortcode without hooking it up to 'init' ?

### ISSUE THREAD

**Issue by vishalbasnet23** [DevinVinson/WordPress-Plugin-Boilerplate#328]

**Comment by DevinVinson** [comment]
Really you could add a function to run at any time if you wanted it not to go through the loader class like here: https://github.com/DevinVinson/WordPress-Plugin-Boilerplate/issues/262#issuecomment-89438555

**Comment by vishalbasnet23** [comment]
Thank you for the reply Devin. Really appreciated the quick response.
