### ISSUE TITLE
Correct way to add an admin notice?

### ISSUE THREAD

**Issue by davetgreen** [DevinVinson/WordPress-Plugin-Boilerplate#331]
Hi @DevinVinson 

First of all, thank you so much for the work you've put into this. For a plugin development newbie such as myself it's really, really useful.

I'd like to have a simple admin notice fire on plugin activation, but I'm not sure how to approach this within the boilerplate.

I understand I'll need to add this to my constructor...

`add_action( 'admin_notices', array( $this, 'activation_notice' ) );`

...as well as adding the static function it calls...

````
	public static function activation_notice() {
	    echo "<div class='updated'><p>Notice to be shown</p></div>";
	}
````
I've tried this in both the My_Plugin_Activator & My_Plugin_Admin classes, but I get an error along the lines of:

`The plugin generated 451 characters of unexpected output during activation. If you notice “headers already sent” messages, problems with syndication feeds or other issues, try deactivating or removing this plugin.`

The notice does appear when I add the above to the My_Plugin_Admin class, which is positive!
Thanks.

**Comment by slushman** [comment]
Hey Dave,

Hey Dave,

Looks like there may need to be several parts to adding a notice that displays on activation. See this thread:

http://stackoverflow.com/questions/9807064/wordpress-how-to-display-notice-in-admin-panel-on-plugin-activation

I just tried adding the following to one my plugins and it worked for me:

In the activator class, include the admin class file, then call the "add_notice" function:
`require_once plugin_dir_path( dirname( __FILE__ ) ) . 'admin/class-now-hiring-admin.php';
Now_Hiring_Admin::add_notice();`

In the My_Plugin_Class in the include folder, put the add_action calls in the define_admin_hooks function:
`$this->loader->add_action( 'admin_notices', $plugin_admin, 'admin_notice' );
$this->loader->add_action( 'admin_init', $plugin_admin, 'admin_init' );`

In the admin class, put three functions
* admin_notice() - displays any notices
* add_notice() - contains the actual notices and adds them to a temporary plugin option.
* admin_init() - updates the plugin option with any additional notices and calls for displaying the notices

`public function admin_notice() {
         if ($notices= get_option('my_plugin_deferred_admin_notices')) {
		    foreach ($notices as $notice) {
		      echo "<div class='updated'><p>$notice</p></div>";
		    }
		    delete_option('my_plugin_deferred_admin_notices');
		  }
    }

    public static function add_notice() {

    	$notices= get_option('my_plugin_deferred_admin_notices', array());
  		$notices[]= "My Plugin: Custom Activation Message";
  		update_option('my_plugin_deferred_admin_notices', $notices);

    }

    public function admin_init() {
		  $current_version = 1;
		  $version= get_option('my_plugin_version');
		  if ($version != $current_version) {
		    // Do whatever upgrades needed here.
		    update_option('my_plugin_version', $current_version);
		    $this->add_notice();
		  }
		}`

**Comment by davetgreen** [comment]
@slushman , thank you **so** much for that! Crystal clear now and working as expected. Much obliged sir!

One quick follow up question if I may: should every action/filter call be made from the loader in My_Plugin_Class then?

**Comment by DevinVinson** [comment]
Yep! Your main class pulls everything together and loads all your actions and filters into the loader to run.

**Comment by davetgreen** [comment]
@DevinVinson :+1: top man!
