### ISSUE TITLE
How to override pluggable function the right way?

### ISSUE THREAD

**Issue by vishalbasnet23** [DevinVinson/WordPress-Plugin-Boilerplate#332]
I am trying to override wp_new_user_notification() from class-plugin-name-admin.php but I am unable to use if( function_exists('wp_new_user_notification') ) inside the file. So please guide me how can I override pluggable functions. FYI I'm fairly new to Object-Oriented plugin development. Any help would be appreciated.

**Comment by DevinVinson** [comment]
As far as I know you wouldn't be able to do the check from inside a class so you would need to pull it out into the main plugin file outside of the main class scope.
