### ISSUE TITLE
Functions vs action hooks

### ISSUE THREAD

**Issue by riverofjanuary** [DevinVinson/WordPress-Plugin-Boilerplate#333]
Hi,
Thank you for this excellent boilerplate; I am finally trying to write "correct" plugins after hacks for many years.
Since the documentation is still sparse, I just want to confirm, there is no way to simply run a procedural function OTHER than using hooks, right?

So rather than running my_function_name() in, say, header.php of my theme, I'd do_action('my_action') and hook 'my_action' to 'my_function_name' public function?

I ask because I reviewed the WP plugin best practices (which linked me here,incidentally) but they dont really discuss the larger theme of using EVERYTHING as hooks/filters. Thanks in advance for clarification (and pointers to other discussions of this issue).

**Comment by DevinVinson** [comment]
Yes, that is correct.

Your individual functions will be attached to being output at specific points which are all coordinated by the loader class.
