### ISSUE TITLE
Build Tool On Main SIte

### ISSUE THREAD

**Issue by robwent** [DevinVinson/WordPress-Plugin-Boilerplate#334]
It seems like building a new plugin using this involves spending the first 30 mins getting your head around the structue, renaming files and going through each file and renaming classes and variables.

If you built a build tool into the main website, similar to underscores, that renames everything and gives you in installable package then it would save a lot of time.

(not sure how to add a feature request label!)

**Comment by robwent** [comment]
Yay! http://wppb.me/

You should add a link to that on the main website to stop people pestering you about it.

**Comment by DevinVinson** [comment]
I somewhat prefer anyones first interaction be with the non renamed data. That way a name choice doesn't confuse right away.

But maybe eventually :smile:

**Comment by agiannis** [comment]
The first interaction thing is well thought, but I think the link should be at "Recommended Tools" to prevent people from loosing time.
In my frustration I started building a somewhat rename tool only to think why nobody built it.
Maybe a simple php script outside the plugin directory will do the job, too.
