### ISSUE TITLE
Register custom post type 

### ISSUE THREAD

**Issue by michaelkk** [DevinVinson/WordPress-Plugin-Boilerplate#335]
Hi 

Im using boilerplate plugin for a new project and I'm kind of struggling in registering a custom post type
In "Plugin_Name_Admin" i have some method to register new post type/shortcodes and then I run them through "define_admin_hooks" method inside "Plugin_Name" class:

        $plugin_admin = new Plugin_Name_Admin( $this->get_plugin_name(), $this->get_version() );

		$this->loader->add_action( 'admin_enqueue_scripts', $plugin_admin, 'enqueue_styles' );
		$this->loader->add_action( 'admin_enqueue_scripts', $plugin_admin, 'enqueue_scripts' );

		$this->loader->add_action( 'init', $plugin_admin, 'ol_locations_init' );
		$this->loader->add_action( 'cmb2_init', $plugin_admin, 'add_options_page_metabox' );
		$this->loader->add_action( 'manage_locations_posts_custom_column' , $plugin_admin, 'ol_custom_columns', 10, 2 );
		$this->loader->add_filter( 'manage_locations_posts_columns' , $plugin_admin, 'ol_add_columns' );
		$this->loader->add_filter( 'wp_insert_post_data', $plugin_admin, 'ol_shortcode_generator' );

For some reason it doesn't register nothing... nor an error...

Can someone help me? )

Thanks a lot

**Comment by DevinVinson** [comment]
Do you have the register code somewhere I can see as well? Is it on init?

**Comment by michaelkk** [comment]
Hi, they are all inside the hooks function
Should they be in init?

**Comment by goranefbl** [comment]
This plugin is adding CPT, poke around: https://github.com/slushman/now-hiring

**Comment by widoz** [comment]
I agree with @DevinVinson, Custom post types must be registered during init or anything will be registered. Have a look at the codex 

*Create or modify a post type. register_post_type should only be invoked through the 'init' action.*
