### ISSUE TITLE
Documentations Standards Link Broken

### ISSUE THREAD

**Issue by alexjustesen** [DevinVinson/WordPress-Plugin-Boilerplate#344]
The link for "document standards" on the website points to a page that no longer exists.

**Comment by DevinVinson** [comment]
Good catch. I'll update the site with the new link to the handbook: https://make.wordpress.org/core/handbook/best-practices/coding-standards/php/

**Comment by alexjustesen** [comment]
Thanks, and thank you for providing the framework. Makes plugin dev much much easier!
