### ISSUE TITLE
"1" is displayed in public pages using shortcode.

### ISSUE THREAD

**Issue by glouk7** [DevinVinson/WordPress-Plugin-Boilerplate#345]
i am creating a custom plugin based on boilerplate plugin, and i use a shortcode to display public data.
$this->loader->add_action( 'test-plugin', $plugin_public, 'display_front_page' );
add_shortcode( 'test-plugin', array( $plugin_public, 'display_front_page') );

The issue is that on every public page, that the shortcode is used, at the end of the page i get the number 1.
I really cannot find where is this number 1 produced from.

Any idea?

**Comment by DevinVinson** [comment]
Without seeing the full code I couldn't even begin to guess really. If you have a link to a repo that would be the only way I could offer a suggestion.
