### ISSUE TITLE
Build a service that can easily change the plugin_name and start coding the plugin.

### ISSUE THREAD

**Issue by ucheng** [DevinVinson/WordPress-Plugin-Boilerplate#348]
Hi All,

Everytime I start a new plugin, I need to change the plugin_name to my real plugin name.
Is there any service like [http://underscores.me/](http://underscores.me/), so I can just input my plugin name, download the zip and then start coding my plugin?

Thank you!

**Comment by LeeRobertsMe** [comment]
Hi uCheng, 

There definitely is, check out www.wppb.me it's exactly what your looking for.

.Me

**Comment by joseluis** [comment]
You have a couple of [resources in the wiki](https://github.com/DevinVinson/WordPress-Plugin-Boilerplate/wiki/Public-Resources). The most used one is [wppb.me](http://wppb.me/).

**Comment by ucheng** [comment]
Thank you guys!

Sorry for missing the wiki.
