### ISSUE TITLE
Advice on setup for large project

### ISSUE THREAD

**Issue by jgarturo** [DevinVinson/WordPress-Plugin-Boilerplate#351]
I've used the Boilerplate a few times before on smaller projects and found it really helpful. I've just taken on a much larger job, which will span several months and involve multiple contributors. I have some questions about how to best use this framework to maintain a large codebase.

1. Classes and such: This project is going to be a lot bigger than just admin/public, so I've begun breaking it out into additional classes. For example, we do a lot of heavy modifications to Advanced Custom Fields. I've created a new Plugin_Name_Admin_ACF class in the /admin/ directory and instantiated it in define_admin_hooks() right under the main admin class. That's working fine for our custom fields, etc. Now I need to start hacking away at WooCommerce. This time, some of the changes will be on the admin side and some will be on the public side. Does it make more sense to have Plugin_Name_Admin_Woo and Plugin_Name_Public_Woo as separate classes, or should I made a new directory (say, "core") and include it there?

2. Shared functions: We have some functions that will be used throughout the plugin (like getting and formatting saved options, for example). What's the best way for including these so they'll be accessible to all classes in the plugin without messing up the organizational structure?

Thanks!

**Comment by DevinVinson** [comment]
Bit large of a topic to cover here but in general I always suggest looking at other projects of similar type and scale. So EDD, WooCommerce etc.

If you are struggling with where to put your classes remember that your class should have a single responsibility. If that is still is causing issues then I default to admin unless it is explicitly public.

A group of shared functions could go in a file in your includes folder or a couple of classes depending on what they are doing.

With that many classes I would also suggest adding an autoloader into the main plugin file so you don't need to do a bunch of includes everywhere :)
