### ISSUE TITLE
Activation Notice

### ISSUE THREAD

**Issue by devcon7** [DevinVinson/WordPress-Plugin-Boilerplate#357]
Hello Devin,

I am trying to output a notice on upgrading the plugin from the previous version.

I tested using "-actiator.php," echoing a message within public static function activate(), but it generates an error:
"The plugin generated ### characters of unexpected output during activation. If you notice “headers already sent” messages, problems with syndication feeds or other issues, try deactivating or removing this plugin."

What is the best practice way of creating the notice?

Please advise!

**Comment by webmarka** [comment]
There cannot be any output on plugin activation, so you may use some hooks to do the job.

See more info here in a [post from our plugin guru and helder, Tom McFarlin!] (https://tommcfarlin.com/plugin-activation-message/)
