### ISSUE TITLE
Should we really define all hooks in the main class?

### ISSUE THREAD

**Issue by pieroit** [DevinVinson/WordPress-Plugin-Boilerplate#358]
I really like the possibilities offered by the boilerplate. Speaking with some other members of the community we found a disagreement on where to define the hooks and filters.

The boilerplate has a class `Plugin_Name_Loader` which keeps track of all the hooks and filters the plugin uses. An instance of this class is an attribute (`$loader`) of the main class `Plugin_Name`. There are two possibilities:

### Centralization 
Define *all* hooks and filters in `Plugin_Name::define_admin_hooks` and `Plugin_Name::define_public_hooks`. This is good when the plugin is small/medium sized, because the hooks are all in one class.

### Distribution
Since the `$loader` is an attribute of the main class, it is possible to use it to add hooks from within other classes. When the plugin gets big it's awful to keep all the hooks declaration (tens of them) in one file. In `Plugin_Name` I would just add the *main* hooks, and let smaller objects define their own hooks in their constructor.
As an example, I would hook  a custom metabox system to `init` in the main class, but let the metabox system itself access the `$loader` to add and remove hooks internally without cluttering the main class.

What do you guys think?
Happy to discuss about this. :)

**Comment by DevinVinson** [comment]
You can use the loader to handle your hooks anywhere in your plugin as long as it makes sense to do so.

If you are to a point where you are architecting out a large scale plugin then you definitely should be challenging the boilerplate organization to make sure it fits your own needs. 

That said, the intention is definitely to have lots and lots of hooks in your class-plugin-name.php file broken up into the admin/public methods.

**Comment by pieroit** [comment]
Thanks :+1:
