### ISSUE TITLE
Shared functions between admin and public

### ISSUE THREAD

**Issue by jonathan-dejong** [DevinVinson/WordPress-Plugin-Boilerplate#359]
Heyo! 

Been using WPPB for quite a while now and it's a great boilerplate, coodoes! 

I have a question about best practise for when I find myself in need of the same functionality for both public and admin. It's usually private classes that would fetch/set/manipulate data in different ways. 

For example; I have a plugin which speaks to an API from both frontend and backend. I have abstracted out functions for authenticating, fetching login credentials (from wp_options) etc. which I'd like to use in both the public and admin class.

Would the best way to go be to create a separate file in say /includes with it's own class and these functions? Then include the file and instantiate the class in both public and admin.

I'm open to suggestions! 

Thanks!

**Comment by DevinVinson** [comment]
Boom you got it exactly. Shared functionality would go into your includes folder and be pulled in as needed.

**Comment by jonathan-dejong** [comment]
Cool  :+1: 

That's what I'll do then!
