### ISSUE TITLE
Is there a reason add_shortcode was removed from loader class?

### ISSUE THREAD

**Issue by samuelsh** [DevinVinson/WordPress-Plugin-Boilerplate#360]
HI, 
According to [this issue] (https://github.com/DevinVinson/WordPress-Plugin-Boilerplate/issues/262#issuecomment-89438555) `add_shortode` method was provided in `loader` class.
But I can't find it in the latest cloned repo.
Is there a reason for it, and if so, what's the right way to add shortcodes using the boilerplate?

Thanks

**Comment by DevinVinson** [comment]
It was never added in but you can add the add_shortcode method to the class just like that.

**Comment by samuelsh** [comment]
Great, thanks :)
