### ISSUE TITLE
link to a tutorial?

### ISSUE THREAD

**Issue by titaniumbones** [DevinVinson/WordPress-Plugin-Boilerplate#366]
I am puzzling through the boilerplate as best I can with my limited php, and am wondering if (a) there is a tutorial outth ere somewhere that you recommend, and (b) if it would make sense to link to such a tutorial from the README.md, so folks like me can find their way to it.

Thank you for the huge headstart!

**Comment by e4rthdog** [comment]
Hi there are many ways to develop a WP plugin and all are ok. This approach here uses OOP.

Main file is e4afz.php which towards the end of the file gets an instance of the main class.

This main class resides in the includes/class-xxxx.php file ...In THAT file most of the glue magic happens..In this file you will see who is calling whom and you can direct yourself in the other files.

So your question has 2 branches: Are you looking for WP plugin tutorial or for OOP PHP tutorial? Becuase this template just brings these 2 worlds together. If you "feel" lost you have to take alook at either of the previous 2 bracnhes. As soon as you get hold of them you will understand fully the logic of this biolerplate. 

There re a plethora of tutorials out there for both things. This is one of them:

[http://code.tutsplus.com/articles/object-oriented-programming-in-wordpress-building-the-plugin-i--cms-21083](url)

**Comment by DevinVinson** [comment]
@titaniumbones I think looking at example plugins is better than a tutorial for the boilerplate. See: https://github.com/DevinVinson/WordPress-Plugin-Boilerplate/wiki/Example-Plugins

**Comment by titaniumbones** [comment]
thanks to both of you!
