### ISSUE TITLE
Can not create custom post type with CPT Class

### ISSUE THREAD

**Issue by techjewel** [DevinVinson/WordPress-Plugin-Boilerplate#367]
Hello Guys,
I am using [this Class](http://github.com/jjgrainger/wp-custom-post-type-class/) to manage custom post types. So I have load the class like this in load_dependencies.

```
 if(!class_exists('CPT')) {
            require_once plugin_dir_path( dirname( __FILE__ ) ) . 'includes/libs/cpt_class/CPT.php';
        }

```

My Admin Hooks:

```
private function define_admin_hooks() {
    $plugin_admin = new Askia_Admin( $this->get_plugin_name(), $this->get_version() );
        $this->loader->add_action( 'init',  $plugin_admin,  'register_questions_post_type' );
}

```

Lastly My custom post type init function:

```
public function register_questions_post_type() {
        // create a book custom post type
        $people = new CPT(array(
            'post_type_name' => 'person',
            'singular' => 'Person',
            'plural' => 'People',
            'slug' => 'people'
        ));

    }
```

The register_questions_post_type is called but some wired reason The post type is not registered.

Any idea?

**Comment by e4rthdog** [comment]
Just out of curiosity why you dont go the standard WP way?

```
add_action( 'init', 'create_post_type' );
function create_post_type() {
  register_post_type( 'acme_product',
    array(
      'labels' => array(
        'name' => __( 'Products' ),
        'singular_name' => __( 'Product' )
      ),
      'public' => true,
      'has_archive' => true,
    )
  );
}
```

**Comment by techjewel** [comment]
@e4rthdog ,
This is not a question about native WP Way, But I would like to use the CPT class here where I get lot more features to managing my taxonomies.
So the question is why the way does not work? and how we can make it work?

**Comment by DevinVinson** [comment]
I don't have any experience with that class so I would first suggest you make sure you can create a CPT as @e4rthdog suggested and make sure you are calling things in the correct spot and on the correct actions. Then debug from there.

**Comment by haleeben** [comment]
I know I'm late to the party but I had a similar issue and found that if I changed to priority to something before 10 then it would work, not exactly sure why thou.

`$this->loader->add_action( 'init',  $plugin_admin,  'register_questions_post_type', 5 );`

**Comment by widoz** [comment]
If you are using this class https://github.com/jjgrainger/wp-custom-post-type-class you don't need to hook into the 'init' action, as you can see within the __construction the init is hooked there.

`$this->add_action( 'init', array( &$this, 'register_post_type' ) );`

So, simply, call your register_questions_post_type directly from the plugin class.

**Comment by jjgrainger** [comment]
@widoz is right, the class will register post types and taxonomies to the correct actions itself, so you don't need to hook your post types into another action.

So your admin hooks method should look like this:

```
private function define_admin_hooks() {
    $plugin_admin = new Askia_Admin( $this->get_plugin_name(), $this->get_version() );

    // call the method here, the class will hook necessary functions to the correct actions
    $plugin_admin->register_questions_post_type();
}
```

@techjewel Thanks for using the class 👍

**Comment by techjewel** [comment]
@jjgrainger Thanks making the awesome class. I use the class every time I need a custom post type <3
