### ISSUE TITLE
resources for clarifying admin vs. public functionality

### ISSUE THREAD

**Issue by ghost** [DevinVinson/WordPress-Plugin-Boilerplate#368]
Hi, I've just started using the Boilerplate for a complex plugin that will be doing a lot with custom post types & templates and coordinating an integration using V2 of the WP REST API. It's a great start, and while I'm not new to WP or to OOP, I find myself wishing for a really good reference that clarifies the difference between admin and public hooks, and what should be called where. In a similar vein, it would be really helpful to know what kind of code should/can be run in the Activator and Deactivator classes. Does anyone have suggestions for good resources on the admin vs public code subject? Thanks!

**Comment by DevinVinson** [comment]
It really is just opinion. Put the code where it makes sense to you and be opinionated. Much of the time I don't use the public class/folder at all and remove it from a fresh plugin.
