### ISSUE TITLE
wppb.io plugin installation not working

### ISSUE THREAD

**Issue by gordiang** [DevinVinson/WordPress-Plugin-Boilerplate#373]
I cannot install the plugin in a freshly installed Wordpress 4.2.2

NO VALID PLUGIN FOUND

Installing Plugin from uploaded file: WordPress-Plugin-Boilerplate-master.zip
Unpacking the package…
Installing the plugin…
The package could not be installed. No valid plugins were found.
Plugin install failed.
Return to Plugins page
Some of your translations need updating. Sit tight for a few more seconds while we update them as well.
Updating translations for Twenty Fifteen (en_GB)…
Translation updated successfully.
Updating translations for Twenty Fourteen (en_GB)…
Translation updated successfully.
Updating translations for Twenty Sixteen (en_GB)…
Translation updated successfully.

**Comment by DevinVinson** [comment]
The boilerplate isn't a working plugin by itself but it should still install from a fresh fork. Without more information though there is no debugging that could be done here.
