### ISSUE TITLE
Load scripts/styles conditionally

### ISSUE THREAD

**Issue by kosmiq** [DevinVinson/WordPress-Plugin-Boilerplate#379]
Hey all,

Just got started using the Boilerplate and feeling a little lost here. After some trial and error I have gotten myself up to speed in the basics of the boilerplate and it's usage.

However, there's something bugging me that I've been unable to figure out so far. I have created a plugin with its own menu page add_menu_page( ... ) and so far so good.

However, I'd like the admin script to load only on that page instead of on all admin pages. Could someone point me in the right direction?

For now I've resorted to creating a new public function called register_admin_scripts() and calling it when adding the menu page. Like so:
  public function add_plugin_page() {
  	$page = add_menu_page(
....
      array( $this, 'create_admin_page' )
    );
		add_action( 'admin_print_scripts-' . $page, array( $this, 'register_admin_scripts' ) );
  }

It works fine, but I have a feeling I'm just missing something obvious in the default functionality. :)

**Comment by DevinVinson** [comment]
You can also add a method that does something like that but checks against the current screen: https://codex.wordpress.org/Function_Reference/get_current_screen

So that you aren't including it on the add page method.

**Comment by goranefbl** [comment]
Its pretty simple, you can do it this way:

```
public function enqueue_styles($hook) {

	if ( 'settings_page_gens-votely' != $hook && 'post.php' != $hook && 'post-new.php' != $hook ) {
    return;
	}

    wp_enqueue_style( 'wp-color-picker' ); 
	wp_enqueue_style( $this->gens_votely, plugin_dir_url( __FILE__ ) . 'css/gens-votely-admin.css', array(), $this->version, 'all' );

}
```

If its inside settings part, you check the hook for 'settings_page_plugin-slug. You can also see an example if you are on a post screen.

If your plugin is inside main menu, you can check with: 

`if( 'toplevel_page_plugin_slug' != $hook ) ...`

**Comment by kosmiq** [comment]
Thanks for the input. I realized I complicated things when I registered the settings page in a separate class as well (don't ask why please :) ).

Got it solved just fine!
