### ISSUE TITLE
Child Plugin

### ISSUE THREAD

**Issue by devcon7** [DevinVinson/WordPress-Plugin-Boilerplate#380]
Hello,

May I ask you whether you can point me to a good direction for developing a child plugin using this boilerplate? I already have the parent plugin developed based on this boilerplate.

Thank you!

**Comment by AlchemyUnited** [comment]
@devcon7  raises an interesting question/issue, and one that I've coincidently put a bit of thought into recently. It short if there was get_template_part() for plugins the WP plugin world could be much different place. 

Let me explain (quickly and crudely)...

Imagine you're using a plugin and everything is cool except for one of the views. You don't like it. The client doesn't like it. Whatever. Etc. It just doesn't cut it. Currently, the typical "workaround" is to fork the plugin, do the changes and keep going. But it is a fork and you're not cut-off from the original.

Instead, what if there was a function similar to get_template_part()? Perhaps not as versatile, but one that at least looked in a child plugin folder(s) for alt "template parts". For example, if your plugin is in my-plugin, this function would / could check my-plugin-child in much the same way g+t+p() does for parent and child themes.

This function could be baked into this boilerplate and this ideal / capability could be incorporated into architecture / mindset of the plugins that use it. 

Again, this is just an off the top of my head pitch for this idea, but I do believe it has merit.

**Comment by DevinVinson** [comment]
A child plugin would be more like using your "parent" plugins hooks and filters.

Outside of that I would not want to see a parent child setup like we have with themes.

**Comment by AlchemyUnited** [comment]
re: "Outside of that I would not want to see a parent child setup like we have with themes."

I'm kinda compelled to ask...Why not? 

If the only way to "extend" a plugin is to fork it, then that just seems kinda silly. 

Filters? Really? Come on now, we can do better than that, can't we? 

Put another way, if the concept is good enough for themes then why not plugins as well? What makes that architecture (if you will) a bad idea of plugins? It's as if the natural and obvious is suddenly unnatural. That should raise a "Interesting. What if..." eyebrow. ;)

**Comment by AlchemyUnited** [comment]
Why was this closed without ANY discussion? Really? Whoa. I'm in the wrong room.

**Comment by DevinVinson** [comment]
Because a plugin is not a theme. WordPress doesn't have child plugins. Hooks and filters are how you extend plugins. It is just that simple.

I closed it because I'm slowly trying to clean up the issue tracking here. I'd like to work on a big update of the boilerplate and move away from the idea that the github repo is for how-to, best practice, help requests etc. Ideally it is for issues with the code or change discussions.

**Comment by AlchemyUnited** [comment]
So the answer is "That's the way we've always done it." 

Nice. Yup. I'm in the wrong room. Thanks for the update. I wish I could chat more but I've gotta go feed my horse and then take the carriage down to the carriage repairman.
