### ISSUE TITLE
WPB - custom meta boxes - call_user_func() expects parameter 1 to be a valid callback, function 'not found or invalid function name

### ISSUE THREAD

**Issue by 0dp** [DevinVinson/WordPress-Plugin-Boilerplate#393]
Hi Folks,

Didn't feel like necro bumping https://github.com/DevinVinson/WordPress-Plugin-Boilerplate/issues/278 but I am facing similar issues on a fresh WordPress install when trying to create custom meta fields.

/*MY HOOK*/
`	private function define_admin_hooks() {
		$this->loader->add_action( 'add_meta_boxes', $plugin_admin, 'custom_juncker_metaboxes');
	}`

/*IN admin/admin class*/
```
public static function custom_juncker_metaboxes() {
        add_meta_box(
            'custom_meta_box', // $id
            __('Produkt Specifikationer', 'juncker'), // $title 
            'render_juncker_metaboxes', // $callback
            'juncker', // $page
            'normal', // $context
            'high' // $priority
        ); 
    }


     function render_juncker_metaboxes() {
        echo 'hi';
  }  
```

It gives me this fancy error
`Warning: call_user_func() expects parameter 1 to be a valid callback, function 'render_juncker_metaboxes' not found or invalid function name`

**Comment by Korsic** [comment]
Hello :)

you miss "  '  "

private function define_admin_hooks() { 
    $this->loader->add_action( 'add_meta_boxes', $plugin_admin, 'custom_juncker_metaboxes'); 
}

**Comment by Korsic** [comment]
Hello :)

You miss http://joxi.ru/5mdQ8lzuv9Bxv2?d=1

**Comment by 0dp** [comment]
Hey Korsic,

Thanks for pointing that out, but somehow it got lost in my copy/paste from source. The ' is in the original code. So that is not the issue ;)

**Comment by slushman** [comment]
If your callback function is in a class, you'll need to call it like this:

array( $this, 'render_juncker_metaboxes' ), // $callback

**Comment by 0dp** [comment]
That was my thought too, but I am then presented with another error:

`Notice: Undefined variable: this in /juncker/admin/class-juncker-admin.php`

**Comment by widoz** [comment]
You cannot use $this within a static method. Try to use the class name instead 

array( 'Admin_Class', 'render_juncker_metaboxes' )

**Comment by slushman** [comment]
Ah, I overlooked that it was static. @widoz is correct. And why is it static?

**Comment by 0dp** [comment]
I am not that well versed in the OOP paradigm, and so I thought that `render_juncker_metaboxes()` didn't have to be part of the instance since it is called directly and is never altered.

But as I read not I can see that trying to do what I did will always throw an error and is super bad practice. So thanks guys.

@widoz, I did in fact try __CLASS__ but that gave some error too (don't recall what though)

So I ended up doing:


function custom_juncker_metaboxes() {
        add_meta_box(
            'custom_meta_box', // $id
            __('Produkt Specifikationer', 'juncker'), // $title 
            array($this, 'render_juncker_metaboxes'), // $callback
            'juncker', // $page
            'normal', // $context
            'high' // $priority
        ); 
    }


     function render_juncker_metaboxes() {
        echo 'hi';
  }  

Thanks 💃

**Comment by widoz** [comment]
@0dp Just to clarify, the __CLASS__  way didn't work because of the method 'render_juncker_metaboxes' was not static too. I missed it, sorry.
