### ISSUE TITLE
Include $hook attribute in action 'admin_enqueue_scripts' call function

### ISSUE THREAD

**Issue by aurovrata** [DevinVinson/WordPress-Plugin-Boilerplate#399]
Hello,

the action 'admin_enqueue_scripts' used to enqueue js in admin pages can call a function with a $hook attribute to [filter admin pages](https://codex.wordpress.org/Plugin_API/Action_Reference/admin_enqueue_scripts#Example:_Target_a_Specific_Admin_Page).  Can you include this into the boilerplate, file `class-plugin-name-admin.php` ([line: 85](https://github.com/DevinVinson/WordPress-Plugin-Boilerplate/blob/master/plugin-name/admin/class-plugin-name-admin.php#L85)).

**Comment by DevinVinson** [comment]
If you'd like to make a PR I'll take a look :)

**Comment by aurovrata** [comment]
Sure thing, shall close this issue here and put in a PR.  Thanks for great BP code btw.
