### ISSUE TITLE
Breaking down a large class.

### ISSUE THREAD

**Issue by rnaby** [DevinVinson/WordPress-Plugin-Boilerplate#404]
I've fallen in to a peculiar problem. I'm writing a plugin, and the `Admin` class right now holds 25+ methods. So I need to break them down in multiple files. Right now I'm using `Traits`. But `Traits` are not available in some older versions of `PHP`. So what could be done in this kinda situations ? Any best practices in mind ?

**Comment by pdhayes** [comment]
Can any of there methods be put into a Helper class?

**Comment by rnaby** [comment]
I could be done by a various kinds of ways. Yea, helper classes could be a fix. But I would rather go to `composing` classes into the `Admin` class. I think it would be a better.
