### ISSUE TITLE
Proposing Alternate Action Registration

### ISSUE THREAD

**Issue by JacobPariseau** [DevinVinson/WordPress-Plugin-Boilerplate#405]
It's a real pain to have to write public functions and then go to the includes class and turn them into actions. I've modified the constructor for `class-plugin-name-public.php` here

```
public function __construct( $plugin_name, $version ) {
  $this->plugin_name = $plugin_name;
  $this->version = $version;
  $this->functions = array_filter(get_class_methods($this), function($name) {
    return $name[0] != "_";
  });
  $this->aliases = array(
    'enqueue_styles' => 'wp_enqueue_scripts',
    'enqueue_scripts' => 'wp_enqueue_scripts'
  );
}

```

and then in `class-reddit-featured.php`

```
private function define_public_hooks() {
  $plugin_public = new Plugin_Name_Public( $this->get_plugin_name(), $this->get_version() );
  $functions = $plugin_public->functions;
  $aliases = $plugin_public->aliases;

  foreach ($functions as $function) {
    if(array_key_exists($function, $aliases)) {
      $this->loader->add_action( $aliases[$function], $plugin_public, $function );
    } else {
      $this->loader->add_action( $function, $plugin_public, $function );
    }
  }
}
```

Now any public function in `class-plugin-name-public.php` that does not start with _ will be added as an action with the same name as its function declaration. If I want a different name, I can optionally add a new line to my aliases array in the format `'function name' => 'action name'`

I currently have this working, but I'm no PHP expert so if this is bad practice for any reason please let me know. I can fork the project, modify it, and submit a pull request if you think this is a better way to set the framework.

**Comment by webmarka** [comment]
Thanks @JacobPariseau for your proposal! 

Writing actions and filters into the `class-plugin-name.php` isn't a real pain in my opinion. It's only a matter of one little line of code for each method that you would have to write anyway in any WordPress plugin/theme. 

Having it all defined in one place gives a sort of _index_ where you can easily review what's fired and in which order. Just have to keep the `class-plugin-name.php` file open in the text editor while you code your methods. And in case you want to deactivate a method temporarily, you just have to comment out the action/filter line and you are set.

One thing that seems missing in your proposed code is **a way to define the 3rd and 4th actions/filters parameters** (`$priority` and `$accepted_args`). 

Another thing missing in the proposed code would be **a way to add filters**. The code only adds `add_action()` but no `add_filter()` is present. So you will still have to add them manually. Or setting a way to distinguish filters from actions, maybe by defining a `filter_` prefix for each filter method?

**Comment by JacobPariseau** [comment]
It would be pretty easy to prefix all the actions and filters that you want added automagically, and just run two loops for all of the `action_functionx()` and `filter_functionx()` that you have in the file. That would allow you to still declare your own actions and filters normally outside of the automatic loop, and place them to fire before or after the loop.

What do you think of defining a Hook class with `$priority`, `$accepted_args` properties and optionally `action` or `filter` functions? We could then add new functions by adding a new Hook to the list and the system would parse it automatically.

**Comment by DevinVinson** [comment]
If you don't want them separated out into using the loader class then simply don't use it. The idea is to separate your concerns and what the above outlines is the exact opposite.

Keeping the actions/filters within your classes is perfectly fine if that is how you are designing your plugin.
