### ISSUE TITLE
which IDE do you use for your plugin development

### ISSUE THREAD

**Issue by yankdoodle** [DevinVinson/WordPress-Plugin-Boilerplate#407]
well hello there everyone, I wanted to see which IDE you find easy to develop and debug.

I was using notepad++ nice at first, but I want more debugging features,

So a thumbs up vote for your IDE and which IDE plugin you like best :)

**Comment by enlacee** [comment]
that's a ISSUE?
you are very wrong :face_with_thermometer:

**Comment by DevinVinson** [comment]
I let a lot of question-issues through but this is definitely not the place for something not even code related.
