### ISSUE TITLE
How to require another plugins' file?

### ISSUE THREAD

**Issue by mladimatija** [DevinVinson/WordPress-Plugin-Boilerplate#411]
I'm trying to call another plugin's file but can't seem to find a correct way to call the file. In my plugin's public folder I've created a file called **ajax-response.php** which I call via ajax and said file executes two functions. First outputs the ajax call results and second one is supposed to create a new instance of the CF7DBPlugin() class and submit the data. Contents of ajax-response.php are:

```
require_once(ABSPATH . 'wp-content/plugins/contact-form-7-to-database-extension/CF7DBPlugin.php');

ajax_return_function();
save_to_database();

function ajax_return_function() {
...
}

function save_to_database() {
$data = (object)  array(
    'title' => 'form-name',
    'posted_data' => array(
    'upload1' => $_FILES['upload1']['name'],
    'email' => $_POST['email']),
    'uploaded_files' => array ('fileupload' => $_FILES["upload1"]["tmp_name"] ));
$plugin = new CF7DBPlugin();
$plugin->saveFormData($data);
}
```
What I'm getting back in the console is:

`Notice:  Use of undefined constant ABSPATH - assumed 'ABSPATH' in C:\xampp\apps\wordpress\htdocs\wp-content\plugins\my-plugin\public\ajax-response.php on line 2`

It seems I can't run any of the Wordpress related functions in this file (like plugin_dir_url() ir plugins_dir()). By reading various posts/issues I assume it's because the file ajax-response.php hasn't been initialized by the plugin.

So my question would be what's the best way to initialize this (and other files) manually created in the plugin folder so they can use Wordpress-related functions, following the WPPB best practices?

**Comment by Tmeister** [comment]
Looks like you are calling the PHP file directly and not in the WordPress way.

You should add an action to the hooks `wp_ajax_` and `wp_ajax_nopriv` to be sure that all the WP related function and constants.

Please read [this](https://codex.wordpress.org/AJAX_in_Plugins) to understand the proper way to do Ajax with WordPress.

**Comment by mladimatija** [comment]
Figured it out after a good night sleep! :) I just needed to add ` wp_ajax_ `and `wp_ajax_nopriv` actions to the hooks list and then separated the function that saves the data to the database via CFDB plugin as dependency. Didn't even need to create additional files.
