### ISSUE TITLE
manage_posts_columns

### ISSUE THREAD

**Issue by jameselks** [DevinVinson/WordPress-Plugin-Boilerplate#420]
Hey team

I have a custom post type `e2_events` and I can't remove the author column. I get no data returned (i.e. no posts shown in the posts `/wp-admin/edit.php?post_type=e2_events`) whenever I try and use this:

	$this->loader->add_filter( 'manage_posts_columns', 'set_custom_columns');

And in admin.php:

	public function set_custom_columns( $columns, $post_type ) {
		switch ($post_type) {
			case 'e2_events':
				unset($columns['author']);
				break;
		}
		return $columns;
	}

I also tried using `manage_{$post_type_name}_posts_columns` and the same problem occurred.

Any ideas?

Cheers,
James.

**Comment by badah** [comment]
Missed param in:
`$this->loader->add_filter( 'manage_posts_columns', 'set_custom_columns');`

It should be:
`$this->loader->add_filter( 'manage_posts_columns', $plugin_admin, 'set_custom_columns');`

or:
`$this->loader->add_filter( 'manage_posts_columns', $plugin_public, 'set_custom_columns');`

Are php notices/warnings enabled on your environment?

**Comment by jameselks** [comment]
Thanks @badah 

Now I have this, but still no luck:

`$this->loader->add_filter( 'manage_e2_events_posts_columns', $plugin_admin, 'e2_set_custom_columns', 10, 2 );`

**Comment by badah** [comment]
Hm... Now I can't see the big picture. Did you remove the switch statement from the callback function? 

I don't think it is possible to access `$post_type` as a second parameter. Examples in WP docs are very similar to your case, take a look: [](https://codex.wordpress.org/Plugin_API/Filter_Reference/manage_$post_type_posts_columns)

**Comment by jameselks** [comment]
Ugh, user error. I lost a day of my life to this, but now it works! Yay! Thanks for your help, I really appreciate it.
