### ISSUE TITLE
Enqueue script and css only when shortcode is used

### ISSUE THREAD

**Issue by bluantinoo** [DevinVinson/WordPress-Plugin-Boilerplate#422]
I don't want to spam, so I posted the question here http://wordpress.stackexchange.com/questions/259657/enqueue-script-only-when-shortcode-is-used-with-wp-plugin-boilerplate

anyone succeeded in this?

**Comment by deshario** [comment]
@bluantinoo Any progress ? how to enqueue css and js in shortcode only ?

**Comment by adamradocz** [comment]
@deshario Check out my [template](https://github.com/adamradocz/WordPress-Plugin-Template/blob/master/plugin-name/Frontend/Frontend.php), I added some shortcode specific comment.
