### ISSUE TITLE
Change License to something non-infectious

### ISSUE THREAD

**Issue by Naatan** [DevinVinson/WordPress-Plugin-Boilerplate#423]
It's kinda silly that a project such as this uses an infectious license. MIT would be a lot friendlier. I wonder how many people are unknowningly in violation of their license ..

**Comment by DevinVinson** [comment]
Not something I can change at this point. With WordPress as a whole as the projects spirit animal and namesake I don't imagine any changes from GPL regardless of its infections state.

**Comment by Naatan** [comment]
I just learned Wordpress uses GPL. Wow ..

**Comment by allusernamestakenexceptthis** [comment]
Even though wordpress is GPL. commercial plugins distributed outside wordpress can be of any license. though it is not tested if whether they are in violation. but this is so far what we have.  Private plugins also can be of any license.

**Comment by dingo-d** [comment]
> Even though wordpress is GPL. commercial plugins distributed outside wordpress can be of any license. though it is not tested if whether they are in violation. but this is so far what we have. Private plugins also can be of any license.

Not true. Any plugin/theme hosted on wp.org **must** be GPL compatible 
https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses

**Comment by allusernamestakenexceptthis** [comment]
That's why I said "distributed outside wordpress "

**Comment by dingo-d** [comment]
Oh, sorry, didn't see that. Yeah, outside of wp.org you can do what ever you want with plugins.
