### ISSUE TITLE
Using composer for libraries my plugin is dependent on

### ISSUE THREAD

**Issue by playgamemy** [DevinVinson/WordPress-Plugin-Boilerplate#424]
I see there were few discussion saying currently the boilerplate does not integrate composer and does not support it natively ... but does it stop me from using composer for installing libraries that my plugin dependent on? 

If I decide to use composer, any suggestion on how I should achieve including the autoload.php from composer? should I requires it only for function that depends on libraries managed by composer, or should I require it by putting it as the first line in my class-plugin-name.php?

(hopefully this make sense)

**Comment by jamrizzi** [comment]
The WP Plugin DevKit is essentially the WordPress Plugin Boilerplate with Composer support.

https://github.com/jamrizzi/wp-plugin-devkit

**Comment by sandrodz** [comment]
@jamrizzi isn't this a better place to autoload composer packages: https://github.com/jamrizzi/wp-plugin-devkit/blob/master/plugin-devkit/includes/class-plugin-devkit.php#L97  ?

**Comment by jamrizzi** [comment]
@sandrodz, would you mind filing an issue about this on my repo, https://github.com/jamrizzi/wp-plugin-devkit/issues, so we don't clutter the WordPress-Plugin-Boilerplate repo with issues unrelated to their project?

**Comment by DevinVinson** [comment]
In any current plugins I do the same as what the devkit linked above does. PSR4 and then everything included with composer and a src folder to autoload.
