### ISSUE TITLE
must use plugin and register_activation_hook

### ISSUE THREAD

**Issue by sandrodz** [DevinVinson/WordPress-Plugin-Boilerplate#431]
register_activation_hook doesn't run in mu-plugins, so I had to use admin_init to run activation and setup tables.

What do you think? is there a better way to do this?
putting action there seems weird, but its also the right place :)

<img width="1280" alt="screen shot 2017-05-29 at 12 47 57 am" src="https://cloud.githubusercontent.com/assets/8479569/26532183/1df1239a-440b-11e7-990a-8f7ff9a41f9a.png">

**Comment by DevinVinson** [comment]
In case you still wanted an answer as I'm closing out issues here: I don't recall any issue here as long as you are only ever running the creation/activation once and pass over it otherwise. Since this will run every single time the admin is loaded.
