### ISSUE TITLE
readme.txt doesn't work ?

### ISSUE THREAD

**Issue by Gwenael-Even** [DevinVinson/WordPress-Plugin-Boilerplate#435]
Hello, i'm currently developping a Plugin using BoilerPlate.

But I have an issue : my readme.txt (who have all the description, the changelog etc..) seems to not working, I only got the description (witch is in the header of my main plugin file (plugin-name.php)) when I try to update my plugin (When you click on "view details of 1.5" before updating for example)

I tried with other plugin that dont use BoilerPlate and it works.

Someone got an issue like that or could help me ?

Thanks, Even Gwenaël.

**Comment by jonathanbossenger** [comment]
@Gwenael-Even I assume you mean the content of the readme.txt is not showing up on the WordPress.org plugin repository page? Can you share that url?

Has the readme.txt file been pushed to the plugin SVN repository?

**Comment by Gwenael-Even** [comment]
Hello, I'm not using the SVN repository, Im currently developping a private plugin and I'm using a plugin update-checker (https://github.com/YahnisElsts/plugin-update-checker) solution to auto-update my plugin without the WordPress official repository.

The problem is : when I have an update, there is the option "View details of version xxx or update now" and when I click on this option, I only have "No changelog Available" which is very weird because my readme.txt is based on the one that WordPress give.

I dont know how to fix this problem because when I try to update another private plugin, without boilerplate, the changelog and the description appears and there is no problem.

(All my files are pushed on a private BitBucket repository)

**Comment by jonathanbossenger** [comment]
@Gwenael-Even the plugin boiler plate does not contain a readme.txt, so I assume you created it for your plugin. Perhaps there is something wrong with the readme.txt?

**Comment by Gwenael-Even** [comment]
I dont know, I use the same Readme.txt for my plugin using BoilerPlate (the one where the readme.txt don't work) and my other plugin (the one where the readme.txt is working)

I use this : https://wordpress.org/plugins/files/2017/03/readme.txt

**Comment by Gwenael-Even** [comment]
Well I don't really know why the problem is solved, maybe an encodage problem

Anyways thanks for your times and your reply, keep up the good work, your project was really useful to help me starting the plugin I created
