### ISSUE TITLE
Point to WP CLI Example Plugin

### ISSUE THREAD

**Issue by jhabdas** [DevinVinson/WordPress-Plugin-Boilerplate#438]
Since this hasn't been updated in 2 years it would be advantageous to users to deprecate in favor of [WP CLI Sample Plugin](https://github.com/wp-cli/sample-plugin) or a well-maintained fork.

Here's an example of how to deprecate fairly clearly:
https://github.com/jhabdas/react-native-webpack-starter-kit#this-project-is-deprecated

**Comment by DevinVinson** [comment]
It isn't deprecated or abandoned. But much of the changes I would like to make depend on core doing the same. 

As is core standards have not really updated in the same time.

**Comment by jhabdas** [comment]
History shows last commit was 2 years ago. If not kept up to date users may not find and maintain the WP CLI. I'd argue strongly for at least pointing to it or a fork at the top of your README with a statement of some kind. For others.

**Comment by jhabdas** [comment]
@danielbachhuber would you mind offering your thoughts? You have far more skin in this than I do.

**Comment by DevinVinson** [comment]
This has no bearing on the success of wp cli. I mean...really.

**Comment by jonathanbossenger** [comment]
@jhabdas I don't see how this plugin boilerplate and the WP CLI have anything to do with each other?

**Comment by danielbachhuber** [comment]
@DevinVinson @jonathanbossenger I've had to block this person from the WP-CLI organization because of their behavior. I'd encourage you to do the same if you find their participation to be inappropriate.

**Comment by jhabdas** [comment]
Thanks for the info @jonathanbossenger. I'm in my second month of WordPress and PHP development and have quite a bit to learn. Thanks for not making any assumptions and giving me the benefit of the doubt. Not everyone does.

**Comment by webmarka** [comment]
@jhabdas If I was only at my 2nd month of WordPress and PHP learning, I would only read stuffs here with my eyes wide open, not comment or even worst, suggest enhancements!! ;)

**Comment by jonathanbossenger** [comment]
@jhabdas welcome to world of WordPress. It's always great to learn new things. You will find however that creating issues along the lines of telling the maintainer that he should deprecate his project without understanding a) the purpose of the project and b) reading about the reasons why it may not have been updated in 2 years, is going to rub people up the wrong way.

**Comment by jhabdas** [comment]
I appreciate the candid feedback. Thanks for your understanding and sorry for any doubts raised.
