### ISSUE TITLE
Plugin Version Definition

### ISSUE THREAD

**Issue by sauravrox** [DevinVinson/WordPress-Plugin-Boilerplate#442]
Please Change ` define( PLUGIN_VERSION, '1.0.0' );` to `define( 'PLUGIN_VERSION', '1.0.0' );` at line 33 of plugin-name.php

**Comment by DevinVinson** [comment]
Want to make a PR to fix @jonathanbossenger

**Comment by jonathanbossenger** [comment]
Well that's embarrassing, sorry @DevinVinson I missed this notification.

@Tmeister's PR resolves this issue.

**Comment by sauravrox** [comment]
I was wondering what is to be done to be a contributor of the WordPress
Plugin Boilerplate. Actually I was thinking if I would be added as a
contributor for the issue and the solution I posted for WPPB. I want to
contribute more as well.

Thank you!

On 12 Sep 2017 6:38 p.m., "Devin" <notifications@github.com> wrote:

Closed #442
<https://github.com/DevinVinson/WordPress-Plugin-Boilerplate/issues/442>
via #443
<https://github.com/DevinVinson/WordPress-Plugin-Boilerplate/pull/443>.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/DevinVinson/WordPress-Plugin-Boilerplate/issues/442#event-1245215360>,
or mute the thread

**Comment by DevinVinson** [comment]
I don't have anything concrete or plans to do so for contributors at the moment. In time for sure but I'd rather it be automated on the site so I never need to handle anything manually.

Aside from that any PR merges will always show in the history so I'll make sure to do @ props if the fix wasn't by whomever reported it.
