### ISSUE TITLE
Intended structure of JS

### ISSUE THREAD

**Issue by tim-rohrer** [DevinVinson/WordPress-Plugin-Boilerplate#450]
I realize upfront this may be a combination noob/boilerplate question:

Is the intention for the plugin-name-admin.js file to contain all the javascript *inside* the IIFE? 

Assuming yes, can someone point me towards the approach to expose different functions correctly to the browser? if statements? Is this where the "...and/or other possibilities." comes into play?

Thanks.

**Comment by DevinVinson** [comment]
It depends on what exactly you want to do and how much of it. If you are going to get weighty with some big page specific javascript then I would say go ahead and break it up into those view specific files and enqueue them where needed and not everywhere.

Then the php enqueue would be where you handle the` if ( is some admin page )` output.

**Comment by tim-rohrer** [comment]
Thanks. 

How about the inside vs outside of the IIFE? Or is it whatever we want?

Trying to learn.

**Comment by DevinVinson** [comment]
Handle them as needed but make sure you don't conflict as much as possible.
