### ISSUE TITLE
Constant PLUGIN_NAME_VERSION collision

### ISSUE THREAD

**Issue by dankkomcg** [DevinVinson/WordPress-Plugin-Boilerplate#461]
If you use a few plugins with the same structure that `WordPress-Plugin-Boilerplate`, the constant is defined one more time for every plugin, this produces an output and the plugin isn't activated.

**Comment by jonathanbossenger** [comment]
To prevent conflicts you should change PLUGIN_NAME in the constant to a unique name/key eg. MY_CUSTOM_PLUGIN_VERSION

**Comment by tyrann0us** [comment]
See #453.
