### ISSUE TITLE
[How To] - Correctly perform a plugin dependency check.

### ISSUE THREAD

**Issue by Terminal-Access** [DevinVinson/WordPress-Plugin-Boilerplate#468]
Hey guys, I'm after a little assistance please.

I am writing a plugin to extend the functionality of another, I would like to set up a proper "plugin dependency check within boilerplate but unfortunately lack the knowledge of where to perform such checks as well as what the best practice for performing said checks are.

The plugin I am extending is WooCommerce how would i go about checking that WooCommerce is installed and currently active.

I'm assuming a check would need to be performed when my plugin is activated, other than this would there be any other instances where i would need to perform such a check?

Could I politely ask for some assistance from my fellow, more knowledgeable developers out there!
Thanks
Lee.

**Comment by dingo-d** [comment]
You can check how I did it in my plugin here: https://github.com/dingo-d/Simple-Linked-Variations-for-WooCommerce/blob/master/simple-linked-variations-for-woocommerce.php

```php
/**
 * Checks if the WooCommerce plugin is activated
 *
 * If the WooCommerce plugin is not active, then don't allow the
 * activation of this plugin.
 *
 * @since 1.0.0
 */
function simplewlv_activate() {
  if ( ! function_exists( 'is_plugin_active_for_network' ) ) {
    include_once( ABSPATH . '/wp-admin/includes/plugin.php' );
  }
  if ( current_user_can( 'activate_plugins' ) && ! class_exists( 'WooCommerce' ) ) {
    // Deactivate the plugin.
    deactivate_plugins( plugin_basename( __FILE__ ) );
    // Throw an error in the WordPress admin console.
    $error_message = '<p style="font-family:-apple-system,BlinkMacSystemFont,\'Segoe UI\',Roboto,Oxygen-Sans,Ubuntu,Cantarell,\'Helvetica Neue\',sans-serif;font-size: 13px;line-height: 1.5;color:#444;">' . esc_html__( 'This plugin requires ', 'simplewlv' ) . '<a href="' . esc_url( 'https://wordpress.org/plugins/simplewlv/' ) . '">WooCommerce</a>' . esc_html__( ' plugin to be active.', 'simplewlv' ) . '</p>';
    die( $error_message ); // WPCS: XSS ok.
  }
}
register_activation_hook( __FILE__, 'simplewlv_activate' );
```

**Comment by Terminal-Access** [comment]
That's awesome, most appreciated!!

thank you ever so much xD

Kind regards

Lee.

**Comment by dingo-d** [comment]
Happy to help :)

**Comment by Terminal-Access** [comment]
It's working perfectly, thanks for the help and support, its greatly appreciated!

**Comment by maryisdead** [comment]
I know this is probably frowned upon in Github-Land, but damn, super helpful code, @dingo-d! Couldn't let this go unmentioned. Thank you!

**Comment by alimoshen** [comment]
Hi,

Thanks for this, however is there a way to disable my plugin when I de-activate WooCommerce?
At the moment it's only checking for WooCommerce when I activate the plugin.

Thanks

**Comment by dingo-d** [comment]
To my knowledge you cannot do that. I think I looked at the way to do that as well, but you cannot deactivate your plugin when woocommerce is deactivated.

You could add a notice that woocommerce is needed for your plugin to work.

**Comment by alimoshen** [comment]
Great thanks for your feedback, I've added the notification instead as how you suggested.

**Comment by ngearing** [comment]
@alimoshen You can use the `register_deactivation_hook` to deactivate your plugin when Woocommerce is deactivated. You just need to supply the file & path of the main Woocommerce plugin file eg. `register_deactivation_hook( ABSPATH . '/wp-content/plugins/woocommerce/woocommerce.php' , 'your_deactivate_func' );`

**Comment by siutek** [comment]
Hi @dingo-d !
I use your code, but when i want activate my plugin, Wordpress display message: 
"The plug-in returned 888 unexpected characters when turned on. If there are "headers already sent" signs on some screen on your site, news channels or other problems, try disabling or removing this plug-in." and then activates my plug.

**Comment by Trumani** [comment]
This was very helpful, thank you! I did make one change. Not sure if I did something wrong when adding the snippet, but the link in the error message wouldn't load unless I added " target="_blank"

**Comment by Spartelfant** [comment]
>the link in the error message wouldn't load unless I added " target="_blank"

@Trumani The link probably worked, however the error message is in its own iframe, so you probably didn't see the link load. This is due to how WP activates plugins: it activates them in their own little sandbox to prevent crashing the entire site if a plugin generates a fatal error. The sandbox then returns whatever output (ie `echo 'oops!';`) or error message (ie `die( 'oops!' );`) was produced by the plugin and WP displays that in an iframe inside the notification box.

**Comment by Trumani** [comment]
That makes since. The entire message disappeared when I had clicked on it. Thank you for the explanation!
