### ISSUE TITLE
Check if Gutenberg is active

### ISSUE THREAD

**Issue by leopuleo** [DevinVinson/WordPress-Plugin-Boilerplate#475]
Hello!
I'm working to update a plugin developed using WPPB to the new Gutenberg editor.
I need to check if Gutenberg PHP functions are available (ex: `register_block_type`) but I can't use `function_exists` inside the main plugin class.

Does anyone is facing the same problem? Do you have any idea?

Thank you!

**Comment by celsobessa** [comment]
Maybe checking for `WP_Block_Type_Registry` class works? 

```php
if ( class_exists( 'WP_Block_Type_Registry' ) ){
    // do your things
}
```

Gutenberg `register_block_type` function returns this class in `[lib/blocks.php](https://github.com/WordPress/gutenberg/blob/master/lib/blocks.php#L29)` in line 30.

```php
return WP_Block_Type_Registry::get_instance()->register( $name, $args );
```

**Comment by leopuleo** [comment]
Thanks, @celsobessa
I solved it adding:
```
if (!class_exists('WP_Block_Type_Registry')) {
      return;
}
```
on top of my gutenberg-related functions.
Now the plugin is working as expected:

- When Gutenberg plugin is not active (plugin functions are not running)
- When Gutenberg plugin is active (plugin functions are running)
- When both Gutenberg and [Classic Editor](https://wordpress.org/plugins/classic-editor/) plugins are active (plugin functions are not running)

Many thanks!

**Comment by celsobessa** [comment]
Glad I could help it (maybe you can close the issue? I am not part of WPPB team)
