### ISSUE TITLE
Problem with shortcode registration

### ISSUE THREAD

**Issue by milosaiki** [DevinVinson/WordPress-Plugin-Boilerplate#486]
I am having a problem with shortcode registration.
[Archive.zip](https://github.com/DevinVinson/WordPress-Plugin-Boilerplate/files/2290090/Archive.zip)
I tried both ways described in [this topic](https://github.com/DevinVinson/WordPress-Plugin-Boilerplate/issues/262).
When I add shortcode to the page, the output on the page is shortcode itself.
I used error logs to see where the problem is, and the function inside add_shortcode is not called.
I am total rookie with wordpress.

p.s. 
for this part private function register_test_shortcode(), I tried both public and private function, and it is not working. I also tried to make it static function and then to use __CLASS__ in add_shortcode, but the issue is the same

**Comment by DeoThemes** [comment]
In your register_test_shortcode function you should add the shortcode inself, try:

`
public function register_test_shortcode( $atts, $content = null )
	{
		$atts = shortcode_atts(
			array(),
			$atts,
			'test'
		);
                echo 'test';
	}
`

**Comment by milosaiki** [comment]
@DeoThemes I tried your solution, but the issue remains. I created gist file for easier reading
https://gist.github.com/milosaiki/c15b231a43691c94eeb0284c91b0e39e

error_log('register_shortcodes_1') from public function register_shortcodes() is outputted, but error_log('register_test_shortcode') from public function register_test_shortcode( $atts, $content = null ) is not

**Comment by DeoThemes** [comment]
Because you are calling only one function in **define_public_hooks**
You can call both like so:

```
$this->loader->add_action('init', $plugin_public, 'register_shortcodes');
$this->loader->add_action('init', $plugin_public, 'register_test_shortcode');
```

**Comment by milosaiki** [comment]
@DeoThemes thank you a lot!  The main problem was wordpress editor, because it was adding <span> tag inside of shortcode. I told you, I am total rookie
