### ISSUE TITLE
add actions and/or filters based on user's role

### ISSUE THREAD

**Issue by ghost** [DevinVinson/WordPress-Plugin-Boilerplate#509]
Hello, thank you for this Boilerplate!

I am adding actions and filters inside define_public_hooks()

I would like to add some of those only if the user is logged in and has certain roles, but is_user_logged_in() seems to be undefined at that point in code execution.

How would I go about this?
Is it even possible to add actions and/or filters based on user's role?

**Comment by shawnk45** [comment]
@mikele3 Not sure if this is the best/proper way to do this but in my main plugin file where you require the main class file and run the "run function" I wrap it in a init action like this:
```
function load_all_classes(){
/**
 * The core plugin class
 */
require plugin_dir_path( __FILE__ ) . 'includes/class-GD-cORe.php';
}
add_action('init', 'load_all_classes');

/**
 * Begins execution of the plugin.
 *
 * @since    3.0.0
 */
function run_GD_cORe() {

	$plugin = new GD_cORe();
	$plugin->run();

}
add_action('init', 'run_GD_cORe');
```
This no gives you access to all of those built in WordPress functions like is_user_logged_in() && current_user_can('manage_options')
Hope this helps 🤷‍♂

**Comment by ghost** [comment]
@shawnk45 sorry for the late reply.

thank you for the suggestion! 

While I was trying to see if your idea would work for me, I realized I didn't have the need anymore... I might just need that in the next project though.
