### ISSUE TITLE
Changelog vs Upgrade Notice

### ISSUE THREAD

**Issue by simplenotezy** [DevinVinson/WordPress-Plugin-Boilerplate#525]
What's the difference between the Changelog and Upgrade Notice sections of the readme.txt?

It might have been displayed somewhere, but I failed to find it.

**Comment by DevinVinson** [comment]
Check out https://developer.wordpress.org/plugins/wordpress-org/how-your-readme-txt-works/

As far as I know the upgrade notices isn't parsed for .org and is more of a formality to provide context.

**Comment by simplenotezy** [comment]
Thanks ;)
