### ISSUE TITLE
Is repo still maintained?

### ISSUE THREAD

**Issue by git-no** [DevinVinson/WordPress-Plugin-Boilerplate#532]
May I ask, is this __very interesting__ repo still maintained?
I would bet a lot of people are interested in, also participating.

But: 
88 Issues and counting,
30 pull requests and 
last commit over a year ago.

looks like there are no further plans for the future of this repo?

**Comment by DevinVinson** [comment]
It still does a good job of giving a lot of people a kick start on a class based plugin. I've had some reworks done a few times over the years but have not followed through to moving everything over quite yet.

I don't see any reason to prune PRs or issues unless they get really out of hand. The PRs show a lot of great ideas, different directions, and are a great resource to look through and learn. Same for many of the issues/questions.

**Comment by git-no** [comment]
I see. Thank you very much.
