### ISSUE TITLE
Wordpress plugin development

### ISSUE THREAD

**Issue by bigstardev** [DevinVinson/WordPress-Plugin-Boilerplate#540]
Hello, i am a beginer of wordpress especially plugin development. Please understand beginners' question.
i am creating my first plugin, so what i am very curious is creating a special page using my own plugin.
In other words, can i make one page just by activating my own custom plugin. If so, how can i assign the page url? I think custom page is made only by creating "template.php". So any advice is much appreciated. Thank you

**Comment by adamradocz** [comment]
Do you want to create a settings page in the Admin area or a page in the Frontend?

**Comment by davidetaddei** [comment]
As I understand you want that the plugin creates a new frontend page reacheable by an url defined by the plugin itself. For example the plugin creates a portfolio reacheable by the url www.mydomain.com/portfolio.

**Comment by bigstardev** [comment]
thank you for your response
