### ISSUE TITLE
https://wppb.io uses an invalid SSL certificate

### ISSUE THREAD

**Issue by meagar** [DevinVinson/WordPress-Plugin-Boilerplate#556]
This site uses a self-signed certificate for `example.com`.

SSL is becoming the default, the homepage should *really* use a valid SSL certificate. If you won't do that, then you should at least close port 443 and stop serving an invalid certificate.

<img width="1680" alt="Screen Shot 2021-03-10 at 9 40 46 PM" src="https://user-images.githubusercontent.com/242474/110727497-63ffbe80-81e9-11eb-8186-d65988c08096.png">

**Comment by DevinVinson** [comment]
Thanks for the heads up. Getting it fixed now :)
