### ISSUE TITLE
Is this repo still maintained?

### ISSUE THREAD

**Issue by smileBeda** [DevinVinson/WordPress-Plugin-Boilerplate#560]
I am asking because forks seem faster to accept commits like https://github.com/DevinVinson/WordPress-Plugin-Boilerplate/pull/559 than the actual core repo here.

If it is abandoned I think a notice should be added to the readme.

Thanks!

**Comment by DevinVinson** [comment]
For the most part yep! I probably will not merge in PRs but I'd still love to find an easy workable pattern for an update in the future.

**Comment by CatinhoCR** [comment]
@DevinVinson 
> For the most part yep! I probably will not merge in PRs but I'd still love to find an easy workable pattern for an update in the future.

What do you mean by an "easy workable pattern for an update"?

Im mainly asking to see if theres anything _we_ could try to help with? And/or why not consider PRs?
