### ISSUE TITLE
Hard Fork for continuous development, accepting PRs and following WPCS

### ISSUE THREAD

**Issue by smileBeda** [DevinVinson/WordPress-Plugin-Boilerplate#564]
Would like to inform potential contributors who have had no chance to get their PRs and ideas into the boilerplate, that due to several reasons (the main one being that this repo here does not accept anymore PRs) I have hard-forked the project into https://github.com/TukuToi/better-wp-plugin-boilerplate

The first changes that will be made are:
- strict following of WPCS (current project does not everywhere, for example see #528).
- updating the loader to support ShortCode Registering as well (see #549).
- updating the JS Comments to reflect latest WP JS and not outdated shorthand's (see PR #559 and #558).
- adding a "Plugin Short" $var to use to prefix technical functions and names.

The next steps after above will be to create a Generator just like wppb.me has, with the new boilerplate.

The new project will be _actively maintained and accept all PRs that make sense_. 
Note, this project will be keeping compatibility with WP 4.9 or in other words - ClassicPress - no matter what.

Github has just confirmed as I type here that the fork is now decoupled from the original, this, open for business.

**Comment by DevinVinson** [comment]
Sounds awesome! Just note that I'm open to PRs or even major refactors in the future. But for what it is and does the boilerplate works great as-is until there is some major updates.

**Comment by smileBeda** [comment]
That's news!
Just a few weeks ago, you said you wont merge in PRs #560.
That is one of the main reasons I forked it, I need some changes to be actually reflected in the core boilerplate.
And I think there are some good ideas to be merged in, without bloating the base code.

Well anyway, I forgot to say it before:
big thanks to make all this possible ;)

**Comment by gytisrepecka** [comment]
> Sounds awesome! Just note that I'm open to PRs or even major refactors in the future. But for what it is and does the boilerplate works great as-is until there is some major updates.

Well, it doesn't seem so. Like shortcodes - functionality at very core of WordPress from the beginning. And yet, there are loads of pull-requests still open (including mine) trying to introduce shortcode support into `master`.

**Comment by DevinVinson** [comment]
This is not something I would expect to be used like a library. It doesn't need to have a solution for everything to be a good place to start. The reason I leave PRs open, don't close issues etc is so it is easy to find.
