### ISSUE TITLE
I’m a beginner front end and I’m going to build a full responsive website for an engineering consultant but i have some questions if any one can help please

### ISSUE THREAD

**Issue by ZeiadSamir** [DevinVinson/WordPress-Plugin-Boilerplate#566]
1- Is this kind of websites needs a huge database and wordpress dashboard or that point not very important?
2- And if so , should i build the data base first or after i finish the website and host it ? 
 
* note : this website contains only one form in contact us category that's all .

I will accept any advice ♥️

**Comment by espiat** [comment]
Hello.

The question has less to do with this Git.

This git is a boiler plate for Wordpress plugins.

**Comment by MrGKanev** [comment]
@espiat he is trying to make a website for a client or something and asking for advice. It is not connected with the repo at all. Here is the same comment in [another repo](https://github.com/mettle/sendportal/issues/160#issuecomment-891677840), which is the same way connected with WordPress as this post.
